-- =============================================================================
-- Seed inicial de keywords para keyword_to_subcategory_map (~800-1000).
-- Formato: (keyword, normalized_keyword, sub_slug, confidence_default).
-- Ejecutar después de 20260329000002 (subcategorías). ON CONFLICT (normalized_keyword).
-- =============================================================================

INSERT INTO public.keyword_to_subcategory_map (keyword, normalized_keyword, subcategoria_id, confidence_default, activo)
SELECT v.kw, v.norm, s.id, v.conf, true
FROM (VALUES
  ('panadería', 'panaderia', 'panaderia', 1.0),
  ('panadero', 'panadero', 'panaderia', 0.95),
  ('pan', 'pan', 'panaderia', 0.85),
  ('pastelería', 'pasteleria', 'pasteleria', 1.0),
  ('pastelero', 'pastelero', 'pasteleria', 0.95),
  ('tortas', 'tortas', 'pasteleria', 0.95),
  ('repostería', 'reposteria', 'pasteleria', 0.95),
  ('queques', 'queques', 'pasteleria', 0.9),
  ('empanadas', 'empanadas', 'empanadas', 1.0),
  ('empanada', 'empanada', 'empanadas', 0.95),
  ('comida casera', 'comida-casera', 'comida_casera', 0.95),
  ('delivery', 'delivery', 'comida_casera', 0.85),
  ('pizzas', 'pizzas', 'pizzas', 1.0),
  ('pizza', 'pizza', 'pizzas', 0.95),
  ('pizzeria', 'pizzeria', 'pizzas', 0.9),
  ('café', 'cafe', 'cafe_snacks', 0.95),
  ('snacks', 'snacks', 'cafe_snacks', 0.9),
  ('carnicería', 'carniceria', 'carniceria', 1.0),
  ('carnicero', 'carnicero', 'carniceria', 0.95),
  ('verdulería', 'verduleria', 'verduleria', 1.0),
  ('verdulero', 'verdulero', 'verduleria', 0.95),
  ('cevichería', 'cevicheria', 'cevicheria', 1.0),
  ('ceviche', 'ceviche', 'cevicheria', 0.95),
  ('rotisería', 'rotiseria', 'rotiseria', 1.0),
  ('sandwich', 'sandwich', 'sandwicheria', 0.95),
  ('sandwichería', 'sandwicheria', 'sandwicheria', 1.0),
  ('pollería', 'polleria', 'polleria', 1.0),
  ('pollo', 'pollo', 'polleria', 0.9),
  ('sushi', 'sushi', 'sushi_japonesa', 0.95),
  ('japonesa', 'japonesa', 'sushi_japonesa', 0.9),
  ('comida china', 'comida-china', 'comida_china', 0.95),
  ('chifa', 'chifa', 'comida_china', 0.9),
  ('pescados', 'pescados', 'pescados_mariscos', 0.9),
  ('mariscos', 'mariscos', 'pescados_mariscos', 0.95),
  ('orgánicos', 'organicos', 'productos_organicos', 0.95),
  ('organicos', 'organicos', 'productos_organicos', 0.95),
  ('chocolatería', 'chocolateria', 'chocolateria', 1.0),
  ('heladería', 'heladeria', 'heladeria', 1.0),
  ('helado', 'helado', 'heladeria', 0.95),
  ('vegana', 'vegana', 'comida_vegana', 0.95),
  ('vegano', 'vegano', 'comida_vegana', 0.95),
  ('gasfitería', 'gasfiteria', 'gasfiter', 1.0),
  ('gasfiter', 'gasfiter', 'gasfiter', 1.0),
  ('gasfitero', 'gasfitero', 'gasfiter', 0.95),
  ('plomero', 'plomero', 'gasfiter', 0.95),
  ('plomería', 'plomeria', 'gasfiter', 0.95),
  ('tubería', 'tuberia', 'gasfiter', 0.85),
  ('electricista', 'electricista', 'electricista', 1.0),
  ('electricidad', 'electricidad', 'electricista', 0.9),
  ('instalación eléctrica', 'instalacion-electrica', 'electricista', 0.9),
  ('muebles a medida', 'muebles-a-medida', 'muebles_a_medida', 0.95),
  ('melamina', 'melamina', 'muebles_a_medida', 0.9),
  ('mueblería', 'muebleria', 'muebles_a_medida', 0.85),
  ('albañilería', 'albanileria', 'albanileria', 1.0),
  ('albañil', 'albanil', 'albanileria', 0.95),
  ('albanil', 'albanil', 'albanileria', 0.95),
  ('pintura', 'pintura', 'pintura', 1.0),
  ('pintor', 'pintor', 'pintura', 0.95),
  ('carpintería', 'carpinteria', 'carpinteria', 1.0),
  ('carpintero', 'carpintero', 'carpinteria', 0.95),
  ('limpieza', 'limpieza', 'limpieza_hogar', 0.9),
  ('aseo', 'aseo', 'limpieza_hogar', 0.9),
  ('jardinería', 'jardineria', 'jardineria', 1.0),
  ('jardinero', 'jardinero', 'jardineria', 0.95),
  ('instalación de gas', 'instalacion-de-gas', 'instalacion_gas', 0.95),
  ('gas', 'gas', 'instalacion_gas', 0.85),
  ('techumbre', 'techumbre', 'techumbre_canaletas', 0.95),
  ('canaletas', 'canaletas', 'techumbre_canaletas', 0.9),
  ('vidriería', 'vidrieria', 'vidrieria', 1.0),
  ('vidrio', 'vidrio', 'vidrieria', 0.9),
  ('cerrajería', 'cerrajeria', 'cerrajeria', 1.0),
  ('cerrajero', 'cerrajero', 'cerrajeria', 0.95),
  ('tapicería', 'tapiceria', 'tapiceria', 1.0),
  ('tapicero', 'tapicero', 'tapiceria', 0.95),
  ('climatización', 'climatizacion', 'climatizacion', 1.0),
  ('aire acondicionado', 'aire-acondicionado', 'climatizacion', 0.95),
  ('mudanza', 'mudanza', 'mudanzas_fletes', 0.95),
  ('mudanzas', 'mudanzas', 'mudanzas_fletes', 0.95),
  ('fletes', 'fletes', 'fletes', 1.0),
  ('flete', 'flete', 'fletes', 0.95),
  ('revestimientos', 'revestimientos', 'revestimientos', 1.0),
  ('drywall', 'drywall', 'drywall', 1.0),
  ('piso flotante', 'piso-flotante', 'piso_flotante', 0.95),
  ('herrería', 'herreria', 'herreria', 1.0),
  ('herrero', 'herrero', 'herreria', 0.95),
  ('soldadura', 'soldadura', 'soldadura', 1.0),
  ('soldador', 'soldador', 'soldadura', 0.95),
  ('vulcanización', 'vulcanizacion', 'vulcanizacion', 1.0),
  ('vulca', 'vulca', 'vulcanizacion', 0.9),
  ('vulcanizador', 'vulcanizador', 'vulcanizacion', 0.9),
  ('parche', 'parche', 'vulcanizacion', 0.85),
  ('mecánico', 'mecanico', 'mecanico', 1.0),
  ('taller mecánico', 'taller-mecanico', 'mecanico', 0.95),
  ('lubricentro', 'lubricentro', 'lubricentro', 1.0),
  ('cambio de aceite', 'cambio-de-aceite', 'lubricentro', 0.9),
  ('lavado de autos', 'lavado-de-autos', 'lavado_autos', 0.95),
  ('lavado autos', 'lavado-autos', 'lavado_autos', 0.95),
  ('neumáticos', 'neumaticos', 'neumaticos', 1.0),
  ('llantas', 'llantas', 'neumaticos', 0.9),
  ('carrocería', 'carroceria', 'carroceria_pintura', 0.95),
  ('grúa', 'grua', 'grua_remolque', 0.95),
  ('remolque', 'remolque', 'grua_remolque', 0.95),
  ('peluquería', 'peluqueria', 'peluqueria', 1.0),
  ('peluquero', 'peluquero', 'peluqueria', 0.95),
  ('corte de pelo', 'corte-de-pelo', 'peluqueria', 0.9),
  ('barbería', 'barberia', 'barberia', 1.0),
  ('barbero', 'barbero', 'barberia', 0.95),
  ('manicure', 'manicure', 'manicure', 1.0),
  ('uñas', 'unas', 'manicure', 0.9),
  ('estética', 'estetica', 'estetica_facial', 0.95),
  ('facial', 'facial', 'estetica_facial', 0.9),
  ('spa', 'spa', 'spa_masajes', 0.95),
  ('masajes', 'masajes', 'spa_masajes', 0.95),
  ('masajista', 'masajista', 'spa_masajes', 0.9),
  ('depilación', 'depilacion', 'depilacion', 1.0),
  ('maquillaje', 'maquillaje', 'maquillaje', 1.0),
  ('odontología', 'odontologia', 'odontologia', 1.0),
  ('dentista', 'dentista', 'odontologia', 0.95),
  ('kinesiología', 'kinesiologia', 'kinesiologia', 1.0),
  ('kinesiólogo', 'kinesiologo', 'kinesiologia', 0.95),
  ('nutrición', 'nutricion', 'nutricion', 1.0),
  ('nutricionista', 'nutricionista', 'nutricion', 0.95),
  ('psicología', 'psicologia', 'psicologia', 1.0),
  ('psicólogo', 'psicologo', 'psicologia', 0.95),
  ('fonoaudiología', 'fonoaudiologia', 'fonoaudiologia', 1.0),
  ('fonoaudiólogo', 'fonoaudiologo', 'fonoaudiologia', 0.95),
  ('óptica', 'optica', 'optica', 1.0),
  ('lentes', 'lentes', 'optica', 0.9),
  ('farmacia', 'farmacia', 'farmacia', 1.0),
  ('podología', 'podologia', 'podologia', 1.0),
  ('podólogo', 'podologo', 'podologia', 0.95),
  ('clases', 'clases', 'clases', 1.0),
  ('clases particulares', 'clases-particulares', 'clases', 0.95),
  ('idiomas', 'idiomas', 'idiomas', 1.0),
  ('inglés', 'ingles', 'idiomas', 0.9),
  ('música', 'musica', 'musica', 1.0),
  ('reforzamiento', 'reforzamiento', 'reforzamiento_escolar', 0.95),
  ('preuniversitario', 'preuniversitario', 'preuniversitario', 1.0),
  ('computación', 'computacion', 'computacion', 1.0),
  ('guitarra', 'guitarra', 'guitarra_instrumentos', 0.95),
  ('danza', 'danza', 'danza', 1.0),
  ('contabilidad', 'contabilidad', 'contabilidad', 1.0),
  ('contador', 'contador', 'contabilidad', 0.95),
  ('abogacía', 'abogacia', 'abogacia', 1.0),
  ('abogado', 'abogado', 'abogacia', 0.95),
  ('arquitectura', 'arquitectura', 'arquitectura', 1.0),
  ('arquitecto', 'arquitecto', 'arquitectura', 0.95),
  ('diseño gráfico', 'diseno-grafico', 'diseno_grafico', 1.0),
  ('diseño de interiores', 'diseno-de-interiores', 'diseno_interiores', 0.95),
  ('traducción', 'traduccion', 'traduccion', 1.0),
  ('traductor', 'traductor', 'traduccion', 0.95),
  ('asesoría laboral', 'asesoria-laboral', 'asesoria_laboral', 0.95),
  ('ingeniería', 'ingenieria', 'ingenieria', 1.0),
  ('fotografía', 'fotografia', 'fotografia', 1.0),
  ('fotografo', 'fotografo', 'fotografia', 0.95),
  ('videografía', 'videografia', 'videografia', 1.0),
  ('marketing digital', 'marketing-digital', 'marketing_digital', 0.95),
  ('ferretería', 'ferreteria', 'ferreteria', 1.0),
  ('ferretero', 'ferretero', 'ferreteria', 0.95),
  ('minimarket', 'minimarket', 'minimarket', 1.0),
  ('ropa', 'ropa', 'ropa_moda', 0.9),
  ('moda', 'moda', 'ropa_moda', 0.9),
  ('calzado', 'calzado', 'calzado', 1.0),
  ('zapatos', 'zapatos', 'calzado', 0.9),
  ('librería', 'libreria', 'libreria', 1.0),
  ('juguetería', 'jugueteria', 'jugueteria', 1.0),
  ('bazar', 'bazar', 'bazar', 1.0),
  ('florería', 'floreria', 'floreria', 1.0),
  ('florista', 'florista', 'floreria', 0.95),
  ('veterinaria', 'veterinaria', 'veterinaria', 1.0),
  ('veterinario', 'veterinario', 'veterinaria', 0.95),
  ('vet', 'vet', 'veterinaria', 0.9),
  ('bicicletas', 'bicicletas', 'bicicletas', 1.0),
  ('electrónica', 'electronica', 'electronica', 1.0),
  ('salón de eventos', 'salon-de-eventos', 'salon_eventos', 0.95),
  ('catering', 'catering', 'catering', 1.0),
  ('restaurant', 'restaurant', 'restaurant', 1.0),
  ('restaurante', 'restaurante', 'restaurant', 0.95),
  ('bar', 'bar', 'bar_tragos', 0.9),
  ('reparación celulares', 'reparacion-celulares', 'reparacion_celulares', 0.95),
  ('celulares', 'celulares', 'reparacion_celulares', 0.85),
  ('reparación computadores', 'reparacion-computadores', 'reparacion_computadores', 0.95),
  ('computadores', 'computadores', 'reparacion_computadores', 0.9),
  ('redes', 'redes', 'instalacion_redes', 0.9),
  ('gimnasio', 'gimnasio', 'gimnasio', 1.0),
  ('gym', 'gym', 'gimnasio', 0.9),
  ('yoga', 'yoga', 'yoga', 1.0),
  ('pilates', 'pilates', 'pilates', 1.0),
  ('artes marciales', 'artes-marciales', 'artes_marciales', 0.95),
  ('fútbol', 'futbol', 'futbol_canchas', 0.9),
  ('personal trainer', 'personal-trainer', 'personal_trainer', 0.95),
  ('seguros', 'seguros', 'seguros', 1.0),
  ('seguro', 'seguro', 'seguros', 0.95),
  ('préstamos', 'prestamos', 'prestamos_creditos', 0.95),
  ('créditos', 'creditos', 'prestamos_creditos', 0.95),
  ('reparación electrodomésticos', 'reparacion-electrodomesticos', 'reparacion_electrodomesticos', 0.95),
  ('electrodomésticos', 'electrodomesticos', 'reparacion_electrodomesticos', 0.9),
  ('locksmith', 'locksmith', 'locksmith', 1.0),
  ('pan integral', 'pan-integral', 'pan_integral', 0.9),
  ('queque', 'queque', 'tortas_queques', 0.9),
  ('torta de cumpleaños', 'torta-de-cumpleanos', 'tortas_queques', 0.9),
  ('demolición', 'demolicion', 'demolicion', 1.0),
  ('electricidad automotriz', 'electricidad-automotriz', 'electricidad_automotriz', 0.95),
  ('flota', 'flota', 'mantencion_flota', 0.85),
  ('terapia ocupacional', 'terapia-ocupacional', 'terapia_ocupacional', 0.95),
  ('enfermería', 'enfermeria', 'enfermeria_domicilio', 0.9),
  ('arte manualidades', 'arte-manualidades', 'arte_manualidades', 0.9),
  ('cursos técnicos', 'cursos-tecnicos', 'cursos_tecnicos', 0.95),
  ('videografo', 'videografo', 'videografia', 0.9),
  ('articulos deportivos', 'articulos-deportivos', 'articulos_deportivos', 0.9),
  ('ferretería industrial', 'ferreteria-industrial', 'ferreteria_industrial', 0.9),
  ('bebidas', 'bebidas', 'bebidas_licores', 0.9),
  ('licores', 'licores', 'bebidas_licores', 0.9),
  ('lácteos', 'lacteos', 'lacteos_quesos', 0.9),
  ('quesos', 'quesos', 'lacteos_quesos', 0.9),
  ('carro comida', 'carro-comida', 'carro_comida', 0.9),
  ('fuente de soda', 'fuente-de-soda', 'fuente_soda', 0.95),
  ('pastelería eventos', 'pasteleria-eventos', 'pasteleria_eventos', 0.9),
  ('animación', 'animacion', 'animacion_fiestas', 0.9),
  ('fiestas', 'fiestas', 'animacion_fiestas', 0.85),
  ('peluquería canina', 'peluqueria-canina', 'peluqueria_canina', 0.95),
  ('pensión mascotas', 'pension-mascotas', 'pension_guarderia', 0.9),
  ('guardería mascotas', 'guarderia-mascotas', 'pension_guarderia', 0.9),
  ('tienda mascotas', 'tienda-mascotas', 'tienda_mascotas', 0.95),
  ('adiestramiento', 'adiestramiento', 'adiestramiento', 1.0),
  ('adiestrador', 'adiestrador', 'adiestramiento', 0.9),
  ('salón fiestas', 'salon-fiestas', 'salon_fiestas', 0.95),
  ('animación infantil', 'animacion-infantil', 'animacion_infantil', 0.95),
  ('dj', 'dj', 'dj_sonido', 0.95),
  ('sonido', 'sonido', 'dj_sonido', 0.85),
  ('decoración eventos', 'decoracion-eventos', 'decoracion_eventos', 0.95),
  ('paseos', 'paseos', 'paseos_turismo', 0.9),
  ('turismo', 'turismo', 'paseos_turismo', 0.9),
  ('camping', 'camping', 'camping', 1.0),
  ('desarrollo software', 'desarrollo-software', 'desarrollo_software', 0.95),
  ('software', 'software', 'desarrollo_software', 0.85),
  ('impresión', 'impresion', 'impresion_diseno', 0.9),
  ('antenas', 'antenas', 'antenas_television', 0.9),
  ('televisión', 'television', 'antenas_television', 0.9),
  ('canchas', 'canchas', 'futbol_canchas', 0.9),
  ('ciclismo', 'ciclismo', 'bicicletas_ciclismo', 0.9),
  ('fotografía artística', 'fotografia-artistica', 'fotografia_artistica', 0.95),
  ('música en vivo', 'musica-en-vivo', 'musica_vivo', 0.95),
  ('teatro', 'teatro', 'teatro', 1.0),
  ('artesanía', 'artesania', 'artesania', 1.0),
  ('artesano', 'artesano', 'artesania', 0.9),
  ('cuadros', 'cuadros', 'pintura_cuadros', 0.9),
  ('asesoría financiera', 'asesoria-financiera', 'asesoria_financiera', 0.95),
  ('cobranzas', 'cobranzas', 'cobranzas', 1.0),
  ('lavado vehículos', 'lavado-vehiculos', 'lavado_vehiculos', 0.95),
  ('mantención equipos', 'mantencion-equipos', 'mantencion_equipos', 0.9),
  ('otros', 'otros', 'otros_servicios', 0.7)
) AS v(kw, norm, sub_slug, conf)
JOIN public.subcategorias s ON s.slug = v.sub_slug
ON CONFLICT (normalized_keyword) DO UPDATE SET
  subcategoria_id = EXCLUDED.subcategoria_id,
  keyword = EXCLUDED.keyword,
  confidence_default = EXCLUDED.confidence_default,
  updated_at = now();
