-- =============================================================================
-- Seed subcategorías oficiales (~250). Ejecutar después de tener categorías.
-- Uso: desde psql o Supabase SQL Editor (después de 20260328000000 o 20260329000001).
-- INSERT con JOIN a categorías por slug; ON CONFLICT (slug) DO NOTHING.
-- =============================================================================

INSERT INTO public.subcategorias (categoria_id, nombre, slug)
SELECT c.id, v.nombre, v.slug
FROM public.categorias c
JOIN (VALUES
  ('alimentacion', 'Panadería', 'panaderia'),
  ('alimentacion', 'Pastelería y repostería', 'pasteleria'),
  ('alimentacion', 'Empanadas', 'empanadas'),
  ('alimentacion', 'Comida casera y delivery', 'comida_casera'),
  ('alimentacion', 'Pizzas', 'pizzas'),
  ('alimentacion', 'Café y snacks', 'cafe_snacks'),
  ('alimentacion', 'Carnicería', 'carniceria'),
  ('alimentacion', 'Verdulería', 'verduleria'),
  ('alimentacion', 'Cevichería', 'cevicheria'),
  ('alimentacion', 'Rotisería', 'rotiseria'),
  ('alimentacion', 'Sandwichería', 'sandwicheria'),
  ('alimentacion', 'Pollería', 'polleria'),
  ('alimentacion', 'Sushi y comida japonesa', 'sushi_japonesa'),
  ('alimentacion', 'Comida china', 'comida_china'),
  ('alimentacion', 'Pescados y mariscos', 'pescados_mariscos'),
  ('alimentacion', 'Productos orgánicos', 'productos_organicos'),
  ('alimentacion', 'Aceitunas y encurtidos', 'aceitunas_encurtidos'),
  ('alimentacion', 'Chocolatería', 'chocolateria'),
  ('alimentacion', 'Heladería', 'heladeria'),
  ('alimentacion', 'Repostería', 'reposteria'),
  ('alimentacion', 'Tortas y queques', 'tortas_queques'),
  ('alimentacion', 'Comida vegana', 'comida_vegana'),
  ('alimentacion', 'Pan integral', 'pan_integral'),
  ('alimentacion', 'Otros alimentación', 'otros_alimentacion'),
  ('hogar_construccion', 'Gasfitería', 'gasfiter'),
  ('hogar_construccion', 'Electricidad', 'electricista'),
  ('hogar_construccion', 'Muebles a medida', 'muebles_a_medida'),
  ('hogar_construccion', 'Albañilería', 'albanileria'),
  ('hogar_construccion', 'Pintura', 'pintura'),
  ('hogar_construccion', 'Carpintería', 'carpinteria'),
  ('hogar_construccion', 'Limpieza de hogar', 'limpieza_hogar'),
  ('hogar_construccion', 'Jardinería', 'jardineria'),
  ('hogar_construccion', 'Instalación de gas', 'instalacion_gas'),
  ('hogar_construccion', 'Techumbre y canaletas', 'techumbre_canaletas'),
  ('hogar_construccion', 'Vidriería', 'vidrieria'),
  ('hogar_construccion', 'Cerrajería', 'cerrajeria'),
  ('hogar_construccion', 'Tapicería', 'tapiceria'),
  ('hogar_construccion', 'Climatización', 'climatizacion'),
  ('hogar_construccion', 'Mudanzas y fletes', 'mudanzas_fletes'),
  ('hogar_construccion', 'Luminarias', 'luminarias'),
  ('hogar_construccion', 'Revestimientos', 'revestimientos'),
  ('hogar_construccion', 'Drywall', 'drywall'),
  ('hogar_construccion', 'Piso flotante', 'piso_flotante'),
  ('hogar_construccion', 'Herrería', 'herreria'),
  ('hogar_construccion', 'Soldadura', 'soldadura'),
  ('hogar_construccion', 'Demolición', 'demolicion'),
  ('hogar_construccion', 'Otros hogar', 'otros_hogar'),
  ('vehiculos_transporte', 'Vulcanización', 'vulcanizacion'),
  ('vehiculos_transporte', 'Mecánico automotriz', 'mecanico'),
  ('vehiculos_transporte', 'Fletes y mudanzas', 'fletes'),
  ('vehiculos_transporte', 'Lubricentro', 'lubricentro'),
  ('vehiculos_transporte', 'Lavado de autos', 'lavado_autos'),
  ('vehiculos_transporte', 'Electricidad automotriz', 'electricidad_automotriz'),
  ('vehiculos_transporte', 'Neumáticos', 'neumaticos'),
  ('vehiculos_transporte', 'Carrocería y pintura', 'carroceria_pintura'),
  ('vehiculos_transporte', 'Grúa y remolque', 'grua_remolque'),
  ('vehiculos_transporte', 'Mantención de flota', 'mantencion_flota'),
  ('vehiculos_transporte', 'Otros vehículos', 'otros_vehiculos'),
  ('salud_belleza', 'Peluquería', 'peluqueria'),
  ('salud_belleza', 'Barbería', 'barberia'),
  ('salud_belleza', 'Manicure y uñas', 'manicure'),
  ('salud_belleza', 'Estética facial', 'estetica_facial'),
  ('salud_belleza', 'Spa y masajes', 'spa_masajes'),
  ('salud_belleza', 'Depilación', 'depilacion'),
  ('salud_belleza', 'Maquillaje', 'maquillaje'),
  ('salud_belleza', 'Odontología', 'odontologia'),
  ('salud_belleza', 'Kinesiología', 'kinesiologia'),
  ('salud_belleza', 'Nutrición', 'nutricion'),
  ('salud_belleza', 'Psicología', 'psicologia'),
  ('salud_belleza', 'Fonoaudiología', 'fonoaudiologia'),
  ('salud_belleza', 'Óptica', 'optica'),
  ('salud_belleza', 'Farmacia', 'farmacia'),
  ('salud_belleza', 'Podología', 'podologia'),
  ('salud_belleza', 'Terapia ocupacional', 'terapia_ocupacional'),
  ('salud_belleza', 'Enfermería a domicilio', 'enfermeria_domicilio'),
  ('salud_belleza', 'Otros salud', 'otros_salud'),
  ('educacion_formacion', 'Clases y capacitación', 'clases'),
  ('educacion_formacion', 'Idiomas', 'idiomas'),
  ('educacion_formacion', 'Música', 'musica'),
  ('educacion_formacion', 'Reforzamiento escolar', 'reforzamiento_escolar'),
  ('educacion_formacion', 'Preuniversitario', 'preuniversitario'),
  ('educacion_formacion', 'Computación', 'computacion'),
  ('educacion_formacion', 'Guitarra y instrumentos', 'guitarra_instrumentos'),
  ('educacion_formacion', 'Danza', 'danza'),
  ('educacion_formacion', 'Arte y manualidades', 'arte_manualidades'),
  ('educacion_formacion', 'Cursos técnicos', 'cursos_tecnicos'),
  ('educacion_formacion', 'Otros educación', 'otros_educacion'),
  ('servicios_profesionales', 'Contabilidad', 'contabilidad'),
  ('servicios_profesionales', 'Abogacía', 'abogacia'),
  ('servicios_profesionales', 'Arquitectura', 'arquitectura'),
  ('servicios_profesionales', 'Diseño gráfico', 'diseno_grafico'),
  ('servicios_profesionales', 'Diseño de interiores', 'diseno_interiores'),
  ('servicios_profesionales', 'Traducción', 'traduccion'),
  ('servicios_profesionales', 'Asesoría laboral', 'asesoria_laboral'),
  ('servicios_profesionales', 'Ingeniería', 'ingenieria'),
  ('servicios_profesionales', 'Fotografía', 'fotografia'),
  ('servicios_profesionales', 'Videografía', 'videografia'),
  ('servicios_profesionales', 'Marketing digital', 'marketing_digital'),
  ('servicios_profesionales', 'Otros profesionales', 'otros_profesionales'),
  ('comercio_retail', 'Ferretería', 'ferreteria'),
  ('comercio_retail', 'Minimarket', 'minimarket'),
  ('comercio_retail', 'Ropa y moda', 'ropa_moda'),
  ('comercio_retail', 'Calzado', 'calzado'),
  ('comercio_retail', 'Librería', 'libreria'),
  ('comercio_retail', 'Juguetería', 'jugueteria'),
  ('comercio_retail', 'Bazar', 'bazar'),
  ('comercio_retail', 'Florería', 'floreria'),
  ('comercio_retail', 'Mascotas y veterinaria', 'mascotas_veterinaria'),
  ('comercio_retail', 'Bicicletas', 'bicicletas'),
  ('comercio_retail', 'Electrónica', 'electronica'),
  ('comercio_retail', 'Artículos deportivos', 'articulos_deportivos'),
  ('comercio_retail', 'Ferretería industrial', 'ferreteria_industrial'),
  ('comercio_retail', 'Bebidas y licores', 'bebidas_licores'),
  ('comercio_retail', 'Lácteos y quesos', 'lacteos_quesos'),
  ('comercio_retail', 'Otros comercio', 'otros_comercio'),
  ('gastronomia_eventos', 'Salón de eventos', 'salon_eventos'),
  ('gastronomia_eventos', 'Catering', 'catering'),
  ('gastronomia_eventos', 'Carro de comida', 'carro_comida'),
  ('gastronomia_eventos', 'Bar y tragos', 'bar_tragos'),
  ('gastronomia_eventos', 'Restaurant', 'restaurant'),
  ('gastronomia_eventos', 'Fuente de soda', 'fuente_soda'),
  ('gastronomia_eventos', 'Pastelería para eventos', 'pasteleria_eventos'),
  ('gastronomia_eventos', 'Animación y fiestas', 'animacion_fiestas'),
  ('gastronomia_eventos', 'Otros gastronomía', 'otros_gastronomia'),
  ('cuidado_mascotas', 'Veterinaria', 'veterinaria'),
  ('cuidado_mascotas', 'Peluquería canina', 'peluqueria_canina'),
  ('cuidado_mascotas', 'Pensión y guardería', 'pension_guarderia'),
  ('cuidado_mascotas', 'Tienda de mascotas', 'tienda_mascotas'),
  ('cuidado_mascotas', 'Adiestramiento', 'adiestramiento'),
  ('cuidado_mascotas', 'Otros mascotas', 'otros_mascotas'),
  ('eventos_recreacion', 'Salón de fiestas', 'salon_fiestas'),
  ('eventos_recreacion', 'Animación infantil', 'animacion_infantil'),
  ('eventos_recreacion', 'Dj y sonido', 'dj_sonido'),
  ('eventos_recreacion', 'Decoración de eventos', 'decoracion_eventos'),
  ('eventos_recreacion', 'Paseos y turismo', 'paseos_turismo'),
  ('eventos_recreacion', 'Camping', 'camping'),
  ('eventos_recreacion', 'Otros eventos', 'otros_eventos'),
  ('tecnologia_comunicaciones', 'Reparación de celulares', 'reparacion_celulares'),
  ('tecnologia_comunicaciones', 'Reparación de computadores', 'reparacion_computadores'),
  ('tecnologia_comunicaciones', 'Instalación de redes', 'instalacion_redes'),
  ('tecnologia_comunicaciones', 'Desarrollo de software', 'desarrollo_software'),
  ('tecnologia_comunicaciones', 'Impresión y diseño', 'impresion_diseno'),
  ('tecnologia_comunicaciones', 'Antenas y televisión', 'antenas_television'),
  ('tecnologia_comunicaciones', 'Otros tecnología', 'otros_tecnologia'),
  ('deportes', 'Gimnasio y entrenamiento', 'gimnasio'),
  ('deportes', 'Yoga', 'yoga'),
  ('deportes', 'Pilates', 'pilates'),
  ('deportes', 'Artes marciales', 'artes_marciales'),
  ('deportes', 'Fútbol y canchas', 'futbol_canchas'),
  ('deportes', 'Bicicletas y ciclismo', 'bicicletas_ciclismo'),
  ('deportes', 'Personal trainer', 'personal_trainer'),
  ('deportes', 'Otros deportes', 'otros_deportes'),
  ('arte_cultura', 'Fotografía artística', 'fotografia_artistica'),
  ('arte_cultura', 'Música en vivo', 'musica_vivo'),
  ('arte_cultura', 'Teatro', 'teatro'),
  ('arte_cultura', 'Artesanía', 'artesania'),
  ('arte_cultura', 'Pintura y cuadros', 'pintura_cuadros'),
  ('arte_cultura', 'Otros arte', 'otros_arte'),
  ('finanzas_seguros', 'Seguros', 'seguros'),
  ('finanzas_seguros', 'Préstamos y créditos', 'prestamos_creditos'),
  ('finanzas_seguros', 'Asesoría financiera', 'asesoria_financiera'),
  ('finanzas_seguros', 'Cobranzas', 'cobranzas'),
  ('finanzas_seguros', 'Otros finanzas', 'otros_finanzas'),
  ('reparaciones_mantencion', 'Lavado de vehículos', 'lavado_vehiculos'),
  ('reparaciones_mantencion', 'Reparación de electrodomésticos', 'reparacion_electrodomesticos'),
  ('reparaciones_mantencion', 'Cerrajería', 'cerrajeria'),
  ('reparaciones_mantencion', 'Locksmith', 'locksmith'),
  ('reparaciones_mantencion', 'Mantención de equipos', 'mantencion_equipos'),
  ('reparaciones_mantencion', 'Otros reparaciones', 'otros_reparaciones'),
  ('otros', 'Otros servicios', 'otros_servicios'),
  ('alimentacion', 'Cocina internacional', 'cocina_internacional'),
  ('alimentacion', 'Comida rápida', 'comida_rapida'),
  ('alimentacion', 'Catering y banquetes', 'catering_banquetes'),
  ('hogar_construccion', 'Aislación', 'aislacion'),
  ('hogar_construccion', 'Impermeabilización', 'impermeabilizacion'),
  ('hogar_construccion', 'Instalación sanitaria', 'instalacion_sanitaria'),
  ('vehiculos_transporte', 'Venta de vehículos', 'venta_vehiculos'),
  ('vehiculos_transporte', 'Auto eléctrico', 'auto_electrico'),
  ('salud_belleza', 'Medicina general', 'medicina_general'),
  ('salud_belleza', 'Terapias alternativas', 'terapias_alternativas'),
  ('educacion_formacion', 'Cursos online', 'cursos_online'),
  ('educacion_formacion', 'Capacitación empresarial', 'capacitacion_empresarial'),
  ('servicios_profesionales', 'Consultoría', 'consultoria'),
  ('servicios_profesionales', 'Notaría', 'notaria'),
  ('comercio_retail', 'Supermercado', 'supermercado'),
  ('comercio_retail', 'Ferretería y construcción', 'ferreteria_construccion'),
  ('gastronomia_eventos', 'Food truck', 'food_truck'),
  ('gastronomia_eventos', 'Cafetería', 'cafeteria'),
  ('cuidado_mascotas', 'Transporte de mascotas', 'transporte_mascotas'),
  ('eventos_recreacion', 'Organización de eventos', 'organizacion_eventos'),
  ('tecnologia_comunicaciones', 'Reparación de notebooks', 'reparacion_notebooks'),
  ('deportes', 'Natación', 'natacion'),
  ('deportes', 'Crossfit', 'crossfit'),
  ('arte_cultura', 'Talleres creativos', 'talleres_creativos'),
  ('finanzas_seguros', 'Inversiones', 'inversiones')
) AS v(cat_slug, nombre, slug) ON c.slug = v.cat_slug
ON CONFLICT (slug) DO NOTHING;
