-- =============================================================================
-- Keywords v1 – Bloque 1: Hogar y construcción (~200)
-- Diccionario Rey del Dato. Cargar en Supabase después de migraciones taxonomía.
-- ON CONFLICT (normalized_keyword) DO UPDATE para evitar duplicados.
-- =============================================================================

INSERT INTO public.keyword_to_subcategory_map (keyword, normalized_keyword, subcategoria_id, confidence_default, activo)
SELECT v.kw, v.norm, s.id, v.conf, true
FROM (VALUES
  -- Gasfitería
  ('gasfiter', 'gasfiter', 'gasfiter', 1.0),
  ('gasfitero', 'gasfitero', 'gasfiter', 0.95),
  ('gasfitería', 'gasfiteria', 'gasfiter', 1.0),
  ('plomero', 'plomero', 'gasfiter', 0.95),
  ('plomería', 'plomeria', 'gasfiter', 0.95),
  ('plomeros', 'plomeros', 'gasfiter', 0.95),
  ('tubería', 'tuberia', 'gasfiter', 0.88),
  ('tuberías', 'tuberias', 'gasfiter', 0.88),
  ('cañerías', 'canerias', 'gasfiter', 0.9),
  ('cañería', 'caneria', 'gasfiter', 0.9),
  ('desagüe', 'desague', 'gasfiter', 0.9),
  ('desagües', 'desagues', 'gasfiter', 0.9),
  ('destape', 'destape', 'gasfiter', 0.85),
  ('destape de cañerías', 'destape-de-canerias', 'gasfiter', 0.9),
  ('instalación sanitaria', 'instalacion-sanitaria', 'gasfiter', 0.9),
  ('instalacion sanitaria', 'instalacion-sanitaria', 'gasfiter', 0.9),
  ('agua caliente', 'agua-caliente', 'gasfiter', 0.82),
  ('calefont', 'calefont', 'gasfiter', 0.88),
  ('calefón', 'calefon', 'gasfiter', 0.88),
  ('llave paso', 'llave-paso', 'gasfiter', 0.8),
  ('reparación de baño', 'reparacion-de-bano', 'gasfiter', 0.88),
  ('reparacion de bano', 'reparacion-de-bano', 'gasfiter', 0.88),
  ('wc', 'wc', 'gasfiter', 0.75),
  ('inodoro', 'inodoro', 'gasfiter', 0.85),
  ('lavatorio', 'lavatorio', 'gasfiter', 0.82),
  ('ducha', 'ducha', 'gasfiter', 0.8),
  ('grifería', 'griferia', 'gasfiter', 0.85),
  ('sifón', 'sifon', 'gasfiter', 0.82),
  -- Electricidad
  ('electricista', 'electricista', 'electricista', 1.0),
  ('electricistas', 'electricistas', 'electricista', 1.0),
  ('electricidad', 'electricidad', 'electricista', 0.92),
  ('instalación eléctrica', 'instalacion-electrica', 'electricista', 0.92),
  ('instalacion electrica', 'instalacion-electrica', 'electricista', 0.92),
  ('empalme eléctrico', 'empalme-electrico', 'electricista', 0.88),
  ('empalme electrico', 'empalme-electrico', 'electricista', 0.88),
  ('tablero eléctrico', 'tablero-electrico', 'electricista', 0.9),
  ('tablero electrico', 'tablero-electrico', 'electricista', 0.9),
  ('casa con luz', 'casa-con-luz', 'electricista', 0.75),
  ('enchufe', 'enchufe', 'electricista', 0.8),
  ('enchufes', 'enchufes', 'electricista', 0.8),
  ('tomacorriente', 'tomacorriente', 'electricista', 0.82),
  ('iluminación', 'iluminacion', 'electricista', 0.85),
  ('iluminacion', 'iluminacion', 'electricista', 0.85),
  ('luminarias', 'luminarias', 'luminarias', 1.0),
  ('ampolletas', 'ampolletas', 'luminarias', 0.9),
  ('led', 'led', 'luminarias', 0.85),
  ('luz', 'luz', 'electricista', 0.7),
  ('corto circuito', 'corto-circuito', 'electricista', 0.9),
  ('cortocircuito', 'cortocircuito', 'electricista', 0.9),
  -- Muebles a medida
  ('muebles a medida', 'muebles-a-medida', 'muebles_a_medida', 0.95),
  ('muebles a la medida', 'muebles-a-la-medida', 'muebles_a_medida', 0.95),
  ('melamina', 'melamina', 'muebles_a_medida', 0.92),
  ('mueblería', 'muebleria', 'muebles_a_medida', 0.88),
  ('mueblero', 'mueblero', 'muebles_a_medida', 0.88),
  ('clóset', 'closet', 'muebles_a_medida', 0.92),
  ('closet', 'closet', 'muebles_a_medida', 0.92),
  ('closets', 'closets', 'muebles_a_medida', 0.92),
  ('cocina integrada', 'cocina-integrada', 'muebles_a_medida', 0.88),
  ('muebles de cocina', 'muebles-de-cocina', 'muebles_a_medida', 0.9),
  ('estante', 'estante', 'muebles_a_medida', 0.8),
  ('estantes', 'estantes', 'muebles_a_medida', 0.8),
  ('modular', 'modular', 'muebles_a_medida', 0.85),
  ('mueble bajo mesada', 'mueble-bajo-mesada', 'muebles_a_medida', 0.88),
  ('mesón', 'meson', 'muebles_a_medida', 0.82),
  ('meson', 'meson', 'muebles_a_medida', 0.82),
  -- Albañilería
  ('albañil', 'albanil', 'albanileria', 0.95),
  ('albañileria', 'albanileria', 'albanileria', 1.0),
  ('albañilería', 'albanileria', 'albanileria', 1.0),
  ('radier', 'radier', 'albanileria', 0.92),
  ('radieres', 'radieres', 'albanileria', 0.9),
  ('tabique', 'tabique', 'albanileria', 0.88),
  ('tabiques', 'tabiques', 'albanileria', 0.88),
  ('pandereta', 'pandereta', 'albanileria', 0.85),
  ('bloque', 'bloque', 'albanileria', 0.8),
  ('ladrillo', 'ladrillo', 'albanileria', 0.85),
  ('ladrillos', 'ladrillos', 'albanileria', 0.85),
  ('pegado de ladrillo', 'pegado-de-ladrillo', 'albanileria', 0.88),
  ('demolición', 'demolicion', 'demolicion', 1.0),
  ('demolicion', 'demolicion', 'demolicion', 1.0),
  ('tirar pared', 'tirar-pared', 'demolicion', 0.85),
  ('sacar tabique', 'sacar-tabique', 'demolicion', 0.88),
  -- Pintura
  ('pintor', 'pintor', 'pintura', 0.95),
  ('pintura', 'pintura', 'pintura', 1.0),
  ('pintores', 'pintores', 'pintura', 0.95),
  ('pintura interior', 'pintura-interior', 'pintura', 0.9),
  ('pintura exterior', 'pintura-exterior', 'pintura', 0.9),
  ('brocha', 'brocha', 'pintura', 0.75),
  ('pintar casa', 'pintar-casa', 'pintura', 0.9),
  ('pintar departamento', 'pintar-departamento', 'pintura', 0.88),
  ('lucir muro', 'lucir-muro', 'pintura', 0.82),
  ('estuco', 'estuco', 'pintura', 0.85),
  ('revestimiento', 'revestimiento', 'revestimientos', 0.95),
  ('revestimientos', 'revestimientos', 'revestimientos', 1.0),
  ('cerámica', 'ceramica', 'revestimientos', 0.9),
  ('ceramica', 'ceramica', 'revestimientos', 0.9),
  ('porcelanato', 'porcelanato', 'revestimientos', 0.9),
  ('piso cerámico', 'piso-ceramico', 'revestimientos', 0.88),
  ('piso flotante', 'piso-flotante', 'piso_flotante', 0.95),
  ('piso flotante laminado', 'piso-flotante-laminado', 'piso_flotante', 0.92),
  ('laminado', 'laminado', 'piso_flotante', 0.85),
  ('entablado', 'entablado', 'piso_flotante', 0.82),
  -- Carpintería
  ('carpintero', 'carpintero', 'carpinteria', 0.95),
  ('carpintería', 'carpinteria', 'carpinteria', 1.0),
  ('carpinteria', 'carpinteria', 'carpinteria', 1.0),
  ('puertas', 'puertas', 'carpinteria', 0.88),
  ('puerta', 'puerta', 'carpinteria', 0.88),
  ('ventanas', 'ventanas', 'carpinteria', 0.88),
  ('ventana', 'ventana', 'carpinteria', 0.88),
  ('marco de puerta', 'marco-de-puerta', 'carpinteria', 0.85),
  ('muebles de madera', 'muebles-de-madera', 'carpinteria', 0.88),
  ('tarima', 'tarima', 'carpinteria', 0.82),
  ('molduras', 'molduras', 'carpinteria', 0.82),
  ('drywall', 'drywall', 'drywall', 1.0),
  ('tabiquería drywall', 'tabiqueria-drywall', 'drywall', 0.95),
  ('tabiqueria drywall', 'tabiqueria-drywall', 'drywall', 0.95),
  ('cielo falso', 'cielo-falso', 'drywall', 0.88),
  ('panel yeso', 'panel-yeso', 'drywall', 0.9),
  ('gypsum', 'gypsum', 'drywall', 0.9),
  -- Limpieza
  ('limpieza', 'limpieza', 'limpieza_hogar', 0.92),
  ('limpieza de hogar', 'limpieza-de-hogar', 'limpieza_hogar', 0.95),
  ('aseo', 'aseo', 'limpieza_hogar', 0.9),
  ('aseo de casa', 'aseo-de-casa', 'limpieza_hogar', 0.9),
  ('asesora del hogar', 'asesora-del-hogar', 'limpieza_hogar', 0.92),
  ('asistente del hogar', 'asistente-del-hogar', 'limpieza_hogar', 0.9),
  ('empleada de casa', 'empleada-de-casa', 'limpieza_hogar', 0.88),
  ('nana', 'nana', 'limpieza_hogar', 0.85),
  ('limpieza profunda', 'limpieza-profunda', 'limpieza_hogar', 0.9),
  ('limpieza post obra', 'limpieza-post-obra', 'limpieza_hogar', 0.88),
  -- Jardinería
  ('jardinero', 'jardinero', 'jardineria', 0.95),
  ('jardinería', 'jardineria', 'jardineria', 1.0),
  ('jardineria', 'jardineria', 'jardineria', 1.0),
  ('poda', 'poda', 'jardineria', 0.9),
  ('podar', 'podar', 'jardineria', 0.9),
  ('césped', 'cesped', 'jardineria', 0.88),
  ('cesped', 'cesped', 'jardineria', 0.88),
  ('pasto', 'pasto', 'jardineria', 0.88),
  ('cortar pasto', 'cortar-pasto', 'jardineria', 0.9),
  ('plantas', 'plantas', 'jardineria', 0.82),
  ('jardín', 'jardin', 'jardineria', 0.88),
  ('jardin', 'jardin', 'jardineria', 0.88),
  ('área verde', 'area-verde', 'jardineria', 0.85),
  ('area verde', 'area-verde', 'jardineria', 0.85),
  -- Instalación de gas
  ('instalación de gas', 'instalacion-de-gas', 'instalacion_gas', 0.95),
  ('instalacion de gas', 'instalacion-de-gas', 'instalacion_gas', 0.95),
  ('gas', 'gas', 'instalacion_gas', 0.85),
  ('conexión de gas', 'conexion-de-gas', 'instalacion_gas', 0.9),
  ('conexion de gas', 'conexion-de-gas', 'instalacion_gas', 0.9),
  ('estufa a gas', 'estufa-a-gas', 'instalacion_gas', 0.85),
  ('calefacción a gas', 'calefaccion-a-gas', 'instalacion_gas', 0.88),
  ('calefaccion a gas', 'calefaccion-a-gas', 'instalacion_gas', 0.88),
  -- Techumbre y canaletas
  ('techumbre', 'techumbre', 'techumbre_canaletas', 0.95),
  ('techumbres', 'techumbres', 'techumbre_canaletas', 0.95),
  ('canaletas', 'canaletas', 'techumbre_canaletas', 0.92),
  ('canaleta', 'canaleta', 'techumbre_canaletas', 0.92),
  ('zinc', 'zinc', 'techumbre_canaletas', 0.88),
  ('techo de zinc', 'techo-de-zinc', 'techumbre_canaletas', 0.9),
  ('techo', 'techo', 'techumbre_canaletas', 0.82),
  ('reparación de techo', 'reparacion-de-techo', 'techumbre_canaletas', 0.9),
  ('reparacion de techo', 'reparacion-de-techo', 'techumbre_canaletas', 0.9),
  ('gotera', 'gotera', 'techumbre_canaletas', 0.88),
  ('goteras', 'goteras', 'techumbre_canaletas', 0.88),
  -- Vidriería
  ('vidriero', 'vidriero', 'vidrieria', 0.95),
  ('vidriería', 'vidrieria', 'vidrieria', 1.0),
  ('vidrio', 'vidrio', 'vidrieria', 0.9),
  ('vidrios', 'vidrios', 'vidrieria', 0.9),
  ('cristal', 'cristal', 'vidrieria', 0.88),
  ('ventana de vidrio', 'ventana-de-vidrio', 'vidrieria', 0.88),
  ('vidrio templado', 'vidrio-templado', 'vidrieria', 0.9),
  -- Cerrajería
  ('cerrajero', 'cerrajero', 'cerrajeria', 0.95),
  ('cerrajería', 'cerrajeria', 'cerrajeria', 1.0),
  ('cerrajeria', 'cerrajeria', 'cerrajeria', 1.0),
  ('cambio de cerradura', 'cambio-de-cerradura', 'cerrajeria', 0.92),
  ('cerradura', 'cerradura', 'cerrajeria', 0.88),
  ('llave duplicada', 'llave-duplicada', 'cerrajeria', 0.88),
  ('copiar llave', 'copiar-llave', 'cerrajeria', 0.88),
  ('abrir puerta', 'abrir-puerta', 'cerrajeria', 0.85),
  ('quedé afuera', 'quede-afuera', 'cerrajeria', 0.82),
  -- Tapicería
  ('tapicero', 'tapicero', 'tapiceria', 0.95),
  ('tapicería', 'tapiceria', 'tapiceria', 1.0),
  ('tapiceria', 'tapiceria', 'tapiceria', 1.0),
  ('tapizado', 'tapizado', 'tapiceria', 0.92),
  ('retapizar', 'retapizar', 'tapiceria', 0.9),
  ('sillón', 'sillon', 'tapiceria', 0.85),
  ('sillon', 'sillon', 'tapiceria', 0.85),
  ('muebles tapizados', 'muebles-tapizados', 'tapiceria', 0.88),
  -- Climatización
  ('climatización', 'climatizacion', 'climatizacion', 1.0),
  ('climatizacion', 'climatizacion', 'climatizacion', 1.0),
  ('aire acondicionado', 'aire-acondicionado', 'climatizacion', 0.95),
  ('instalación aire acondicionado', 'instalacion-aire-acondicionado', 'climatizacion', 0.92),
  ('instalacion aire acondicionado', 'instalacion-aire-acondicionado', 'climatizacion', 0.92),
  ('split', 'split', 'climatizacion', 0.88),
  ('ventilación', 'ventilacion', 'climatizacion', 0.85),
  ('ventilacion', 'ventilacion', 'climatizacion', 0.85),
  ('calefacción', 'calefaccion', 'climatizacion', 0.88),
  ('calefaccion', 'calefaccion', 'climatizacion', 0.88),
  -- Mudanzas y fletes
  ('mudanza', 'mudanza', 'mudanzas_fletes', 0.95),
  ('mudanzas', 'mudanzas', 'mudanzas_fletes', 0.95),
  ('flete', 'flete', 'mudanzas_fletes', 0.92),
  ('fletes', 'fletes', 'mudanzas_fletes', 0.92),
  ('camión de mudanza', 'camion-de-mudanza', 'mudanzas_fletes', 0.9),
  ('camion de mudanza', 'camion-de-mudanza', 'mudanzas_fletes', 0.9),
  ('traslado de muebles', 'traslado-de-muebles', 'mudanzas_fletes', 0.9),
  ('carga', 'carga', 'mudanzas_fletes', 0.8),
  ('camión', 'camion', 'mudanzas_fletes', 0.82),
  ('camion', 'camion', 'mudanzas_fletes', 0.82),
  -- Herrería y soldadura
  ('herrero', 'herrero', 'herreria', 0.95),
  ('herrería', 'herreria', 'herreria', 1.0),
  ('herreria', 'herreria', 'herreria', 1.0),
  ('reja', 'reja', 'herreria', 0.9),
  ('rejas', 'rejas', 'herreria', 0.9),
  ('portón', 'porton', 'herreria', 0.88),
  ('porton', 'porton', 'herreria', 0.88),
  ('soldador', 'soldador', 'soldadura', 0.95),
  ('soldadura', 'soldadura', 'soldadura', 1.0),
  ('soldadura a domicilio', 'soldadura-a-domicilio', 'soldadura', 0.9),
  -- Aislación e impermeabilización
  ('aislación', 'aislacion', 'aislacion', 1.0),
  ('aislacion', 'aislacion', 'aislacion', 1.0),
  ('aislante', 'aislante', 'aislacion', 0.9),
  ('termo aislante', 'termo-aislante', 'aislacion', 0.88),
  ('impermeabilización', 'impermeabilizacion', 'impermeabilizacion', 1.0),
  ('impermeabilizacion', 'impermeabilizacion', 'impermeabilizacion', 1.0),
  ('impermeabilizante', 'impermeabilizante', 'impermeabilizacion', 0.92),
  ('techo filtrando', 'techo-filtrando', 'impermeabilizacion', 0.88),
  ('humedad', 'humedad', 'impermeabilizacion', 0.82)
) AS v(kw, norm, sub_slug, conf)
JOIN public.subcategorias s ON s.slug = v.sub_slug
ON CONFLICT (normalized_keyword) DO UPDATE SET
  keyword = EXCLUDED.keyword,
  subcategoria_id = EXCLUDED.subcategoria_id,
  confidence_default = EXCLUDED.confidence_default,
  updated_at = now();
