-- =============================================================================
-- Keywords v1 – Bloque 2: Automotriz (~200)
-- =============================================================================

INSERT INTO public.keyword_to_subcategory_map (keyword, normalized_keyword, subcategoria_id, confidence_default, activo)
SELECT v.kw, v.norm, s.id, v.conf, true
FROM (VALUES
  -- Vulcanización
  ('vulca', 'vulca', 'vulcanizacion', 0.92),
  ('vulcanización', 'vulcanizacion', 'vulcanizacion', 1.0),
  ('vulcanizacion', 'vulcanizacion', 'vulcanizacion', 1.0),
  ('vulcanizador', 'vulcanizador', 'vulcanizacion', 0.9),
  ('parche neumático', 'parche-neumatico', 'vulcanizacion', 0.88),
  ('parche neumatico', 'parche-neumatico', 'vulcanizacion', 0.88),
  ('pinchar', 'pinchar', 'vulcanizacion', 0.85),
  ('pinchazo', 'pinchazo', 'vulcanizacion', 0.88),
  ('reparar neumático', 'reparar-neumatico', 'vulcanizacion', 0.9),
  ('reparar neumatico', 'reparar-neumatico', 'vulcanizacion', 0.9),
  ('neumáticos', 'neumaticos', 'neumaticos', 0.95),
  ('neumaticos', 'neumaticos', 'neumaticos', 0.95),
  ('neumático', 'neumatico', 'neumaticos', 0.95),
  ('neumatico', 'neumatico', 'neumaticos', 0.95),
  ('cambio de neumáticos', 'cambio-de-neumaticos', 'neumaticos', 0.92),
  ('llantas', 'llantas', 'neumaticos', 0.9),
  ('llanta', 'llanta', 'neumaticos', 0.9),
  ('goma', 'goma', 'neumaticos', 0.85),
  ('gomas', 'gomas', 'neumaticos', 0.85),
  -- Mecánico automotriz
  ('mecánico', 'mecanico', 'mecanico', 1.0),
  ('mecanico', 'mecanico', 'mecanico', 1.0),
  ('mecánico automotriz', 'mecanico-automotriz', 'mecanico', 0.98),
  ('taller mecánico', 'taller-mecanico', 'mecanico', 0.95),
  ('taller mecanico', 'taller-mecanico', 'mecanico', 0.95),
  ('taller', 'taller', 'mecanico', 0.85),
  ('reparación de autos', 'reparacion-de-autos', 'mecanico', 0.92),
  ('reparacion de autos', 'reparacion-de-autos', 'mecanico', 0.92),
  ('reparar auto', 'reparar-auto', 'mecanico', 0.9),
  ('revisión técnica', 'revision-tecnica', 'mecanico', 0.9),
  ('revision tecnica', 'revision-tecnica', 'mecanico', 0.9),
  ('revisión automotriz', 'revision-automotriz', 'mecanico', 0.9),
  ('revision automotriz', 'revision-automotriz', 'mecanico', 0.9),
  ('motor', 'motor', 'mecanico', 0.88),
  ('frenos', 'frenos', 'mecanico', 0.9),
  ('pastillas de freno', 'pastillas-de-freno', 'mecanico', 0.9),
  ('embrague', 'embrague', 'mecanico', 0.88),
  ('caja de cambios', 'caja-de-cambios', 'mecanico', 0.88),
  ('suspensión', 'suspension', 'mecanico', 0.88),
  ('suspension', 'suspension', 'mecanico', 0.88),
  ('alineación', 'alineacion', 'mecanico', 0.9),
  ('alineacion', 'alineacion', 'mecanico', 0.9),
  ('balanceo', 'balanceo', 'mecanico', 0.9),
  ('amortiguadores', 'amortiguadores', 'mecanico', 0.88),
  ('bujías', 'bujias', 'mecanico', 0.85),
  ('bujias', 'bujias', 'mecanico', 0.85),
  ('correa de distribución', 'correa-de-distribucion', 'mecanico', 0.88),
  ('correa de distribucion', 'correa-de-distribucion', 'mecanico', 0.88),
  ('radiador', 'radiador', 'mecanico', 0.85),
  ('bomba de agua', 'bomba-de-agua', 'mecanico', 0.85),
  ('alternador', 'alternador', 'mecanico', 0.82),
  ('partes de auto', 'partes-de-auto', 'mecanico', 0.82),
  -- Fletes y mudanzas
  ('fletes', 'fletes', 'fletes', 1.0),
  ('flete', 'flete', 'fletes', 0.95),
  ('mudanza', 'mudanza', 'fletes', 0.95),
  ('mudanzas', 'mudanzas', 'fletes', 0.95),
  ('camión de carga', 'camion-de-carga', 'fletes', 0.9),
  ('camion de carga', 'camion-de-carga', 'fletes', 0.9),
  ('transporte de carga', 'transporte-de-carga', 'fletes', 0.9),
  ('acarreo', 'acarreo', 'fletes', 0.88),
  ('retiro y entrega', 'retiro-y-entrega', 'fletes', 0.88),
  ('flete a domicilio', 'flete-a-domicilio', 'fletes', 0.9),
  ('camión', 'camion', 'fletes', 0.82),
  ('camion', 'camion', 'fletes', 0.82),
  -- Lubricentro
  ('lubricentro', 'lubricentro', 'lubricentro', 1.0),
  ('cambio de aceite', 'cambio-de-aceite', 'lubricentro', 0.95),
  ('aceite', 'aceite', 'lubricentro', 0.85),
  ('lubricación', 'lubricacion', 'lubricentro', 0.9),
  ('lubricacion', 'lubricacion', 'lubricentro', 0.9),
  ('filtro de aceite', 'filtro-de-aceite', 'lubricentro', 0.88),
  ('filtro de aire', 'filtro-de-aire', 'lubricentro', 0.85),
  -- Lavado de autos
  ('lavado de autos', 'lavado-de-autos', 'lavado_autos', 0.95),
  ('lavado de auto', 'lavado-de-auto', 'lavado_autos', 0.95),
  ('lavado de vehículos', 'lavado-de-vehiculos', 'lavado_autos', 0.92),
  ('lavado de vehiculos', 'lavado-de-vehiculos', 'lavado_autos', 0.92),
  ('lavado de autos a domicilio', 'lavado-de-autos-a-domicilio', 'lavado_autos', 0.92),
  ('lavado a domicilio', 'lavado-a-domicilio', 'lavado_autos', 0.88),
  ('lavado de motor', 'lavado-de-motor', 'lavado_autos', 0.85),
  ('pulido', 'pulido', 'lavado_autos', 0.85),
  ('encerado', 'encerado', 'lavado_autos', 0.85),
  ('túnel de lavado', 'tunel-de-lavado', 'lavado_autos', 0.82),
  ('tunel de lavado', 'tunel-de-lavado', 'lavado_autos', 0.82),
  ('autolavado', 'autolavado', 'lavado_autos', 0.88),
  -- Electricidad automotriz
  ('electricidad automotriz', 'electricidad-automotriz', 'electricidad_automotriz', 0.95),
  ('electricista automotriz', 'electricista-automotriz', 'electricidad_automotriz', 0.95),
  ('batería de auto', 'bateria-de-auto', 'electricidad_automotriz', 0.9),
  ('bateria de auto', 'bateria-de-auto', 'electricidad_automotriz', 0.9),
  ('batería', 'bateria', 'electricidad_automotriz', 0.85),
  ('bateria', 'bateria', 'electricidad_automotriz', 0.85),
  ('alternador auto', 'alternador-auto', 'electricidad_automotriz', 0.85),
  ('arranque', 'arranque', 'electricidad_automotriz', 0.82),
  ('no enciende el auto', 'no-enciende-el-auto', 'electricidad_automotriz', 0.88),
  -- Carrocería y pintura
  ('carrocería', 'carroceria', 'carroceria_pintura', 0.95),
  ('carroceria', 'carroceria', 'carroceria_pintura', 0.95),
  ('pintura de autos', 'pintura-de-autos', 'carroceria_pintura', 0.92),
  ('pintura automotriz', 'pintura-automotriz', 'carroceria_pintura', 0.92),
  ('chapa', 'chapa', 'carroceria_pintura', 0.88),
  ('chapa y pintura', 'chapa-y-pintura', 'carroceria_pintura', 0.95),
  ('abolladura', 'abolladura', 'carroceria_pintura', 0.88),
  ('rayón', 'rayon', 'carroceria_pintura', 0.85),
  ('rayon', 'rayon', 'carroceria_pintura', 0.85),
  ('choque', 'choque', 'carroceria_pintura', 0.82),
  ('reparación de choque', 'reparacion-de-choque', 'carroceria_pintura', 0.9),
  ('reparacion de choque', 'reparacion-de-choque', 'carroceria_pintura', 0.9),
  ('barniz', 'barniz', 'carroceria_pintura', 0.82),
  -- Grúa y remolque
  ('grúa', 'grua', 'grua_remolque', 0.95),
  ('grua', 'grua', 'grua_remolque', 0.95),
  ('grúas', 'gruas', 'grua_remolque', 0.95),
  ('gruas', 'gruas', 'grua_remolque', 0.95),
  ('remolque', 'remolque', 'grua_remolque', 0.92),
  ('remolque de autos', 'remolque-de-autos', 'grua_remolque', 0.92),
  ('acarreo de vehículos', 'acarreo-de-vehiculos', 'grua_remolque', 0.9),
  ('acarreo de vehiculos', 'acarreo-de-vehiculos', 'grua_remolque', 0.9),
  ('auto quedó abajo', 'auto-quedo-abajo', 'grua_remolque', 0.85),
  ('rescate vehicular', 'rescate-vehicular', 'grua_remolque', 0.9),
  ('zorrillo', 'zorrillo', 'grua_remolque', 0.88),
  -- Mantención de flota
  ('mantención de flota', 'mantencion-de-flota', 'mantencion_flota', 0.95),
  ('mantencion de flota', 'mantencion-de-flota', 'mantencion_flota', 0.95),
  ('flota de vehículos', 'flota-de-vehiculos', 'mantencion_flota', 0.88),
  ('flota de vehiculos', 'flota-de-vehiculos', 'mantencion_flota', 0.88),
  ('mantención preventiva', 'mantencion-preventiva', 'mantencion_flota', 0.9),
  ('mantencion preventiva', 'mantencion-preventiva', 'mantencion_flota', 0.9),
  -- Venta y auto eléctrico
  ('venta de vehículos', 'venta-de-vehiculos', 'venta_vehiculos', 0.92),
  ('venta de vehiculos', 'venta-de-vehiculos', 'venta_vehiculos', 0.92),
  ('auto eléctrico', 'auto-electrico', 'auto_electrico', 0.92),
  ('auto electrico', 'auto-electrico', 'auto_electrico', 0.92),
  ('vehículo eléctrico', 'vehiculo-electrico', 'auto_electrico', 0.9),
  ('vehiculo electrico', 'vehiculo-electrico', 'auto_electrico', 0.9),
  ('cargador eléctrico', 'cargador-electrico', 'auto_electrico', 0.85),
  ('cargador electrico', 'cargador-electrico', 'auto_electrico', 0.85),
  -- Lavado de vehículos (reparaciones_mantencion)
  ('lavado de vehículos', 'lavado-de-vehiculos', 'lavado_vehiculos', 0.92),
  ('lavado vehiculos', 'lavado-vehiculos', 'lavado_vehiculos', 0.9)
) AS v(kw, norm, sub_slug, conf)
JOIN public.subcategorias s ON s.slug = v.sub_slug
ON CONFLICT (normalized_keyword) DO UPDATE SET
  keyword = EXCLUDED.keyword,
  subcategoria_id = EXCLUDED.subcategoria_id,
  confidence_default = EXCLUDED.confidence_default,
  updated_at = now();
