-- =============================================================================
-- Keywords v1 – Bloque 3: Comida (~200)
-- Lenguaje chileno: rotación, colación, once, completos, etc.
-- =============================================================================

INSERT INTO public.keyword_to_subcategory_map (keyword, normalized_keyword, subcategoria_id, confidence_default, activo)
SELECT v.kw, v.norm, s.id, v.conf, true
FROM (VALUES
  -- Panadería
  ('panadería', 'panaderia', 'panaderia', 1.0),
  ('panaderia', 'panaderia', 'panaderia', 1.0),
  ('panadero', 'panadero', 'panaderia', 0.95),
  ('pan', 'pan', 'panaderia', 0.88),
  ('pan amasado', 'pan-amasado', 'panaderia', 0.92),
  ('hallulla', 'hallulla', 'panaderia', 0.9),
  ('doblada', 'doblada', 'panaderia', 0.88),
  ('colación', 'colacion', 'panaderia', 0.85),
  ('colaciones', 'colaciones', 'panaderia', 0.85),
  ('dulces de panadería', 'dulces-de-panaderia', 'panaderia', 0.88),
  ('dulces de panaderia', 'dulces-de-panaderia', 'panaderia', 0.88),
  ('pan de masa madre', 'pan-de-masa-madre', 'panaderia', 0.88),
  ('marraqueta', 'marraqueta', 'panaderia', 0.92),
  ('pan batido', 'pan-batido', 'panaderia', 0.85),
  ('dobladas', 'dobladas', 'panaderia', 0.88),
  ('pan integral', 'pan-integral', 'pan_integral', 0.92),
  -- Pastelería y repostería
  ('pastelería', 'pasteleria', 'pasteleria', 1.0),
  ('pasteleria', 'pasteleria', 'pasteleria', 1.0),
  ('pastelero', 'pastelero', 'pasteleria', 0.95),
  ('repostería', 'reposteria', 'pasteleria', 0.95),
  ('reposteria', 'reposteria', 'pasteleria', 0.95),
  ('tortas', 'tortas', 'pasteleria', 0.95),
  ('torta', 'torta', 'pasteleria', 0.95),
  ('tortas y queques', 'tortas-y-queques', 'tortas_queques', 0.95),
  ('queque', 'queque', 'pasteleria', 0.9),
  ('queques', 'queques', 'pasteleria', 0.9),
  ('kuchen', 'kuchen', 'pasteleria', 0.92),
  ('brazo de reina', 'brazo-de-reina', 'pasteleria', 0.88),
  ('berlín', 'berlin', 'pasteleria', 0.88),
  ('berlines', 'berlines', 'pasteleria', 0.88),
  ('torta de novios', 'torta-de-novios', 'pasteleria', 0.9),
  ('torta de cumpleaños', 'torta-de-cumpleanos', 'pasteleria', 0.9),
  ('torta de cumpleanos', 'torta-de-cumpleanos', 'pasteleria', 0.9),
  ('dulces', 'dulces', 'pasteleria', 0.82),
  ('reposteria', 'reposteria', 'pasteleria', 0.95),
  ('pasteleria para eventos', 'pasteleria-para-eventos', 'pasteleria_eventos', 0.92),
  -- Empanadas
  ('empanadas', 'empanadas', 'empanadas', 1.0),
  ('empanada', 'empanada', 'empanadas', 0.95),
  ('empanada de pino', 'empanada-de-pino', 'empanadas', 0.92),
  ('empanada de queso', 'empanada-de-queso', 'empanadas', 0.9),
  ('empanada de mariscos', 'empanada-de-mariscos', 'empanadas', 0.9),
  ('empanadas fritas', 'empanadas-fritas', 'empanadas', 0.9),
  ('empanadas de horno', 'empanadas-de-horno', 'empanadas', 0.9),
  ('pastel de choclo', 'pastel-de-choclo', 'empanadas', 0.82),
  -- Comida casera y delivery
  ('comida casera', 'comida-casera', 'comida_casera', 0.95),
  ('delivery', 'delivery', 'comida_casera', 0.9),
  ('comida a domicilio', 'comida-a-domicilio', 'comida_casera', 0.92),
  ('almuerzo a domicilio', 'almuerzo-a-domicilio', 'comida_casera', 0.9),
  ('cena a domicilio', 'cena-a-domicilio', 'comida_casera', 0.9),
  ('comida para llevar', 'comida-para-llevar', 'comida_casera', 0.88),
  ('rotación', 'rotacion', 'comida_casera', 0.85),
  ('rotacion', 'rotacion', 'comida_casera', 0.85),
  ('casera', 'casera', 'comida_casera', 0.82),
  ('tipo casero', 'tipo-casero', 'comida_casera', 0.82),
  -- Pizzas
  ('pizza', 'pizza', 'pizzas', 0.95),
  ('pizzas', 'pizzas', 'pizzas', 1.0),
  ('pizzería', 'pizzeria', 'pizzas', 0.95),
  ('pizzeria', 'pizzeria', 'pizzas', 0.95),
  ('pizza a domicilio', 'pizza-a-domicilio', 'pizzas', 0.9),
  ('pizza delivery', 'pizza-delivery', 'pizzas', 0.9),
  ('pizza napolitana', 'pizza-napolitana', 'pizzas', 0.88),
  ('pizza al paso', 'pizza-al-paso', 'pizzas', 0.85),
  -- Café y snacks
  ('café', 'cafe', 'cafe_snacks', 0.95),
  ('cafe', 'cafe', 'cafe_snacks', 0.95),
  ('cafetería', 'cafeteria', 'cafe_snacks', 0.92),
  ('cafeteria', 'cafeteria', 'cafe_snacks', 0.92),
  ('once', 'once', 'cafe_snacks', 0.9),
  ('snacks', 'snacks', 'cafe_snacks', 0.88),
  ('sandwich', 'sandwich', 'sandwicheria', 0.92),
  ('sandwichería', 'sandwicheria', 'sandwicheria', 1.0),
  ('sandwicheria', 'sandwicheria', 'sandwicheria', 1.0),
  ('completos', 'completos', 'sandwicheria', 0.92),
  ('completo', 'completo', 'sandwicheria', 0.92),
  ('hot dog', 'hot-dog', 'sandwicheria', 0.88),
  ('churrasco', 'churrasco', 'sandwicheria', 0.9),
  ('barros luco', 'barros-luco', 'sandwicheria', 0.88),
  ('barros jarpa', 'barros-jarpa', 'sandwicheria', 0.88),
  ('ave mayo', 'ave-mayo', 'sandwicheria', 0.85),
  ('italiano', 'italiano', 'sandwicheria', 0.85),
  -- Carnicería
  ('carnicería', 'carniceria', 'carniceria', 1.0),
  ('carniceria', 'carniceria', 'carniceria', 1.0),
  ('carnicero', 'carnicero', 'carniceria', 0.95),
  ('carne', 'carne', 'carniceria', 0.88),
  ('carnes', 'carnes', 'carniceria', 0.88),
  ('vacuno', 'vacuno', 'carniceria', 0.88),
  ('cerdo', 'cerdo', 'carniceria', 0.85),
  ('pollo', 'pollo', 'polleria', 0.9),
  ('pollería', 'polleria', 'polleria', 1.0),
  ('polleria', 'polleria', 'polleria', 1.0),
  ('aves', 'aves', 'polleria', 0.82),
  -- Verdulería
  ('verdulería', 'verduleria', 'verduleria', 1.0),
  ('verduleria', 'verduleria', 'verduleria', 1.0),
  ('verdulero', 'verdulero', 'verduleria', 0.95),
  ('verduras', 'verduras', 'verduleria', 0.9),
  ('frutas', 'frutas', 'verduleria', 0.9),
  ('frutería', 'fruteria', 'verduleria', 0.88),
  ('fruteria', 'fruteria', 'verduleria', 0.88),
  ('feria', 'feria', 'verduleria', 0.82),
  -- Cevichería y mariscos
  ('cevichería', 'cevicheria', 'cevicheria', 1.0),
  ('cevicheria', 'cevicheria', 'cevicheria', 1.0),
  ('ceviche', 'ceviche', 'cevicheria', 0.95),
  ('mariscos', 'mariscos', 'pescados_mariscos', 0.95),
  ('pescados', 'pescados', 'pescados_mariscos', 0.92),
  ('pescados y mariscos', 'pescados-y-mariscos', 'pescados_mariscos', 0.95),
  ('pescado fresco', 'pescado-fresco', 'pescados_mariscos', 0.9),
  ('mariscal', 'mariscal', 'cevicheria', 0.85),
  ('machas', 'machas', 'pescados_mariscos', 0.88),
  ('ostiones', 'ostiones', 'pescados_mariscos', 0.88),
  ('locos', 'locos', 'pescados_mariscos', 0.85),
  ('congrio', 'congrio', 'pescados_mariscos', 0.88),
  ('reineta', 'reineta', 'pescados_mariscos', 0.85),
  -- Rotisería
  ('rotisería', 'rotiseria', 'rotiseria', 1.0),
  ('rotiseria', 'rotiseria', 'rotiseria', 1.0),
  ('rotisería a domicilio', 'rotiseria-a-domicilio', 'rotiseria', 0.92),
  ('pollo asado', 'pollo-asado', 'rotiseria', 0.9),
  ('papas fritas', 'papas-fritas', 'rotiseria', 0.8),
  ('ensalada', 'ensalada', 'rotiseria', 0.75),
  -- Sushi y comida japonesa
  ('sushi', 'sushi', 'sushi_japonesa', 0.95),
  ('comida japonesa', 'comida-japonesa', 'sushi_japonesa', 0.92),
  ('japonesa', 'japonesa', 'sushi_japonesa', 0.88),
  ('roll', 'roll', 'sushi_japonesa', 0.88),
  ('rolls', 'rolls', 'sushi_japonesa', 0.88),
  ('sashimi', 'sashimi', 'sushi_japonesa', 0.9),
  ('tempura', 'tempura', 'sushi_japonesa', 0.85),
  ('ramen', 'ramen', 'sushi_japonesa', 0.88),
  -- Comida china
  ('comida china', 'comida-china', 'comida_china', 0.95),
  ('chifa', 'chifa', 'comida_china', 0.92),
  ('chino', 'chino', 'comida_china', 0.82),
  ('chop suey', 'chop-suey', 'comida_china', 0.88),
  ('arroz frito', 'arroz-frito', 'comida_china', 0.85),
  -- Productos orgánicos y vegana
  ('orgánico', 'organico', 'productos_organicos', 0.92),
  ('organico', 'organico', 'productos_organicos', 0.92),
  ('productos orgánicos', 'productos-organicos', 'productos_organicos', 0.95),
  ('productos organicos', 'productos-organicos', 'productos_organicos', 0.95),
  ('vegana', 'vegana', 'comida_vegana', 0.92),
  ('vegano', 'vegano', 'comida_vegana', 0.92),
  ('comida vegana', 'comida-vegana', 'comida_vegana', 0.95),
  ('comida vegetariana', 'comida-vegetariana', 'comida_vegana', 0.88),
  ('vegetariano', 'vegetariano', 'comida_vegana', 0.88),
  -- Chocolatería, heladería
  ('chocolatería', 'chocolateria', 'chocolateria', 1.0),
  ('chocolateria', 'chocolateria', 'chocolateria', 1.0),
  ('chocolate', 'chocolate', 'chocolateria', 0.9),
  ('heladería', 'heladeria', 'heladeria', 1.0),
  ('heladeria', 'heladeria', 'heladeria', 1.0),
  ('helado', 'helado', 'heladeria', 0.95),
  ('helados', 'helados', 'heladeria', 0.95),
  ('ice cream', 'ice-cream', 'heladeria', 0.85),
  -- Aceitunas, cocina internacional, comida rápida
  ('aceitunas', 'aceitunas', 'aceitunas_encurtidos', 0.9),
  ('encurtidos', 'encurtidos', 'aceitunas_encurtidos', 0.9),
  ('cocina internacional', 'cocina-internacional', 'cocina_internacional', 0.92),
  ('comida rápida', 'comida-rapida', 'comida_rapida', 0.92),
  ('comida rapida', 'comida-rapida', 'comida_rapida', 0.92),
  ('fast food', 'fast-food', 'comida_rapida', 0.88),
  ('hamburguesa', 'hamburguesa', 'comida_rapida', 0.85),
  ('hamburguesas', 'hamburguesas', 'comida_rapida', 0.85),
  -- Catering
  ('catering', 'catering', 'catering', 0.95),
  ('catering y banquetes', 'catering-y-banquetes', 'catering_banquetes', 0.95),
  ('banquetes', 'banquetes', 'catering_banquetes', 0.92),
  ('servicio de catering', 'servicio-de-catering', 'catering', 0.92),
  ('eventos gastronómicos', 'eventos-gastronomicos', 'catering', 0.88),
  ('eventos gastronomicos', 'eventos-gastronomicos', 'catering', 0.88),
  -- Restaurant y fuente de soda
  ('restaurant', 'restaurant', 'restaurant', 0.95),
  ('restaurante', 'restaurante', 'restaurant', 0.95),
  ('fuente de soda', 'fuente-de-soda', 'fuente_soda', 0.92),
  ('fuente de soda', 'fuente-de-soda', 'fuente_soda', 0.92),
  ('soda', 'soda', 'fuente_soda', 0.85),
  ('bar', 'bar', 'bar_tragos', 0.85),
  ('tragos', 'tragos', 'bar_tragos', 0.88),
  ('bar y tragos', 'bar-y-tragos', 'bar_tragos', 0.92)
) AS v(kw, norm, sub_slug, conf)
JOIN public.subcategorias s ON s.slug = v.sub_slug
ON CONFLICT (normalized_keyword) DO UPDATE SET
  keyword = EXCLUDED.keyword,
  subcategoria_id = EXCLUDED.subcategoria_id,
  confidence_default = EXCLUDED.confidence_default,
  updated_at = now();
