-- =============================================================================
-- Keywords v1 – Bloque 4: Belleza (~200)
-- =============================================================================

INSERT INTO public.keyword_to_subcategory_map (keyword, normalized_keyword, subcategoria_id, confidence_default, activo)
SELECT v.kw, v.norm, s.id, v.conf, true
FROM (VALUES
  -- Peluquería
  ('peluquería', 'peluqueria', 'peluqueria', 1.0),
  ('peluqueria', 'peluqueria', 'peluqueria', 1.0),
  ('peluquero', 'peluquero', 'peluqueria', 0.95),
  ('peluquera', 'peluquera', 'peluqueria', 0.95),
  ('corte de pelo', 'corte-de-pelo', 'peluqueria', 0.92),
  ('corte de cabello', 'corte-de-cabello', 'peluqueria', 0.92),
  ('tintura', 'tintura', 'peluqueria', 0.9),
  ('tinte', 'tinte', 'peluqueria', 0.9),
  ('peinado', 'peinado', 'peluqueria', 0.9),
  ('peinados', 'peinados', 'peluqueria', 0.9),
  ('balayage', 'balayage', 'peluqueria', 0.88),
  ('mechas', 'mechas', 'peluqueria', 0.9),
  ('alisado', 'alisado', 'peluqueria', 0.9),
  ('keratina', 'keratina', 'peluqueria', 0.88),
  ('permanente', 'permanente', 'peluqueria', 0.85),
  ('cabello', 'cabello', 'peluqueria', 0.8),
  ('pelo', 'pelo', 'peluqueria', 0.8),
  -- Barbería
  ('barbería', 'barberia', 'barberia', 1.0),
  ('barberia', 'barberia', 'barberia', 1.0),
  ('barbero', 'barbero', 'barberia', 0.95),
  ('corte de hombre', 'corte-de-hombre', 'barberia', 0.9),
  ('corte masculino', 'corte-masculino', 'barberia', 0.9),
  ('barba', 'barba', 'barberia', 0.9),
  ('arreglo de barba', 'arreglo-de-barba', 'barberia', 0.92),
  ('afeitado', 'afeitado', 'barberia', 0.9),
  ('afeitada', 'afeitada', 'barberia', 0.88),
  ('degradé', 'degrade', 'barberia', 0.88),
  ('degrade', 'degrade', 'barberia', 0.88),
  ('rasurado', 'rasurado', 'barberia', 0.88),
  -- Manicure y uñas
  ('manicure', 'manicure', 'manicure', 1.0),
  ('manicurista', 'manicurista', 'manicure', 0.95),
  ('uñas', 'unas', 'manicure', 0.9),
  ('unas', 'unas', 'manicure', 0.9),
  ('uñas acrílicas', 'unas-acrilicas', 'manicure', 0.92),
  ('unas acrilicas', 'unas-acrilicas', 'manicure', 0.92),
  ('esmaltado', 'esmaltado', 'manicure', 0.9),
  ('esmaltado semipermanente', 'esmaltado-semipermanente', 'manicure', 0.92),
  ('gel', 'gel', 'manicure', 0.85),
  ('uñas gel', 'unas-gel', 'manicure', 0.9),
  ('pedicure', 'pedicure', 'manicure', 0.9),
  ('pedicurista', 'pedicurista', 'manicure', 0.88),
  ('kapping', 'kapping', 'manicure', 0.85),
  ('nail art', 'nail-art', 'manicure', 0.85),
  ('cuidado de uñas', 'cuidado-de-unas', 'manicure', 0.88),
  -- Estética facial
  ('estética facial', 'estetica-facial', 'estetica_facial', 0.95),
  ('estetica facial', 'estetica-facial', 'estetica_facial', 0.95),
  ('facial', 'facial', 'estetica_facial', 0.9),
  ('limpieza facial', 'limpieza-facial', 'estetica_facial', 0.92),
  ('tratamiento facial', 'tratamiento-facial', 'estetica_facial', 0.9),
  ('hidratación facial', 'hidratacion-facial', 'estetica_facial', 0.88),
  ('hidratacion facial', 'hidratacion-facial', 'estetica_facial', 0.88),
  ('dermaplaning', 'dermaplaning', 'estetica_facial', 0.85),
  ('microdermabrasión', 'microdermabrasion', 'estetica_facial', 0.88),
  ('microdermabrasion', 'microdermabrasion', 'estetica_facial', 0.88),
  ('punta de diamante', 'punta-de-diamante', 'estetica_facial', 0.85),
  ('peeling', 'peeling', 'estetica_facial', 0.88),
  ('acné', 'acne', 'estetica_facial', 0.82),
  ('acne', 'acne', 'estetica_facial', 0.82),
  ('manchas', 'manchas', 'estetica_facial', 0.82),
  ('antiage', 'antiage', 'estetica_facial', 0.85),
  ('antiedad', 'antiedad', 'estetica_facial', 0.85),
  -- Spa y masajes
  ('spa', 'spa', 'spa_masajes', 0.95),
  ('masajes', 'masajes', 'spa_masajes', 0.95),
  ('masaje', 'masaje', 'spa_masajes', 0.95),
  ('spa y masajes', 'spa-y-masajes', 'spa_masajes', 0.95),
  ('masajista', 'masajista', 'spa_masajes', 0.92),
  ('masaje relajante', 'masaje-relajante', 'spa_masajes', 0.9),
  ('masaje descontracturante', 'masaje-descontracturante', 'spa_masajes', 0.92),
  ('masaje terapéutico', 'masaje-terapeutico', 'spa_masajes', 0.9),
  ('masaje terapeutico', 'masaje-terapeutico', 'spa_masajes', 0.9),
  ('reflexología', 'reflexologia', 'spa_masajes', 0.88),
  ('reflexologia', 'reflexologia', 'spa_masajes', 0.88),
  ('piedras calientes', 'piedras-calientes', 'spa_masajes', 0.88),
  ('aromaterapia', 'aromaterapia', 'spa_masajes', 0.85),
  ('sauna', 'sauna', 'spa_masajes', 0.82),
  ('jacuzzi', 'jacuzzi', 'spa_masajes', 0.82),
  ('día de spa', 'dia-de-spa', 'spa_masajes', 0.88),
  ('dia de spa', 'dia-de-spa', 'spa_masajes', 0.88),
  -- Depilación
  ('depilación', 'depilacion', 'depilacion', 1.0),
  ('depilacion', 'depilacion', 'depilacion', 1.0),
  ('depiladora', 'depiladora', 'depilacion', 0.95),
  ('depilación con cera', 'depilacion-con-cera', 'depilacion', 0.9),
  ('depilacion con cera', 'depilacion-con-cera', 'depilacion', 0.9),
  ('cera', 'cera', 'depilacion', 0.85),
  ('depilación definitiva', 'depilacion-definitiva', 'depilacion', 0.92),
  ('depilacion definitiva', 'depilacion-definitiva', 'depilacion', 0.92),
  ('láser', 'laser', 'depilacion', 0.88),
  ('laser', 'laser', 'depilacion', 0.88),
  ('depilación láser', 'depilacion-laser', 'depilacion', 0.9),
  ('depilacion laser', 'depilacion-laser', 'depilacion', 0.9),
  ('ceja', 'ceja', 'depilacion', 0.82),
  ('cejas', 'cejas', 'depilacion', 0.82),
  ('diseño de cejas', 'diseno-de-cejas', 'depilacion', 0.88),
  ('diseno de cejas', 'diseno-de-cejas', 'depilacion', 0.88),
  -- Maquillaje
  ('maquillaje', 'maquillaje', 'maquillaje', 1.0),
  ('maquilladora', 'maquilladora', 'maquillaje', 0.95),
  ('maquillista', 'maquillista', 'maquillaje', 0.95),
  ('maquillaje social', 'maquillaje-social', 'maquillaje', 0.9),
  ('maquillaje de novias', 'maquillaje-de-novias', 'maquillaje', 0.92),
  ('maquillaje para eventos', 'maquillaje-para-eventos', 'maquillaje', 0.9),
  ('automaquillaje', 'automaquillaje', 'maquillaje', 0.85),
  ('tutorial de maquillaje', 'tutorial-de-maquillaje', 'maquillaje', 0.8),
  ('cejas maquillaje', 'cejas-maquillaje', 'maquillaje', 0.82),
  ('pestañas', 'pestanas', 'maquillaje', 0.85),
  ('pestañas postizas', 'pestanas-postizas', 'maquillaje', 0.88),
  ('pestanas postizas', 'pestanas-postizas', 'maquillaje', 0.88),
  ('extensiones de pestañas', 'extensiones-de-pestanas', 'maquillaje', 0.88),
  ('extensiones de pestanas', 'extensiones-de-pestanas', 'maquillaje', 0.88),
  ('brow lamination', 'brow-lamination', 'maquillaje', 0.82),
  -- Lash / pestañas (maquillaje)
  ('lash', 'lash', 'maquillaje', 0.85),
  ('lifting de pestañas', 'lifting-de-pestanas', 'maquillaje', 0.88),
  ('lifting de pestanas', 'lifting-de-pestanas', 'maquillaje', 0.88)
) AS v(kw, norm, sub_slug, conf)
JOIN public.subcategorias s ON s.slug = v.sub_slug
ON CONFLICT (normalized_keyword) DO UPDATE SET
  keyword = EXCLUDED.keyword,
  subcategoria_id = EXCLUDED.subcategoria_id,
  confidence_default = EXCLUDED.confidence_default,
  updated_at = now();
