-- =============================================================================
-- Keywords v1 – Bloque 5: Mascotas (~200)
-- =============================================================================

INSERT INTO public.keyword_to_subcategory_map (keyword, normalized_keyword, subcategoria_id, confidence_default, activo)
SELECT v.kw, v.norm, s.id, v.conf, true
FROM (VALUES
  -- Veterinaria
  ('veterinaria', 'veterinaria', 'veterinaria', 1.0),
  ('veterinario', 'veterinario', 'veterinaria', 0.95),
  ('vet', 'vet', 'veterinaria', 0.9),
  ('clínica veterinaria', 'clinica-veterinaria', 'veterinaria', 0.92),
  ('clinica veterinaria', 'clinica-veterinaria', 'veterinaria', 0.92),
  ('veterinaria a domicilio', 'veterinaria-a-domicilio', 'veterinaria', 0.92),
  ('mascota enferma', 'mascota-enferma', 'veterinaria', 0.85),
  ('perro enfermo', 'perro-enfermo', 'veterinaria', 0.85),
  ('gato enfermo', 'gato-enfermo', 'veterinaria', 0.85),
  ('vacunas para perros', 'vacunas-para-perros', 'veterinaria', 0.9),
  ('vacunas para gatos', 'vacunas-para-gatos', 'veterinaria', 0.9),
  ('desparasitación', 'desparasitacion', 'veterinaria', 0.88),
  ('desparasitacion', 'desparasitacion', 'veterinaria', 0.88),
  ('castración', 'castracion', 'veterinaria', 0.9),
  ('castracion', 'castracion', 'veterinaria', 0.9),
  ('esterilización', 'esterilizacion', 'veterinaria', 0.9),
  ('esterilizacion', 'esterilizacion', 'veterinaria', 0.9),
  ('consulta veterinaria', 'consulta-veterinaria', 'veterinaria', 0.92),
  ('emergencia veterinaria', 'emergencia-veterinaria', 'veterinaria', 0.9),
  ('radiografía mascota', 'radiografia-mascota', 'veterinaria', 0.85),
  ('radiografia mascota', 'radiografia-mascota', 'veterinaria', 0.85),
  ('ecografía mascota', 'ecografia-mascota', 'veterinaria', 0.85),
  ('ecografia mascota', 'ecografia-mascota', 'veterinaria', 0.85),
  ('cirugía veterinaria', 'cirugia-veterinaria', 'veterinaria', 0.9),
  ('cirugia veterinaria', 'cirugia-veterinaria', 'veterinaria', 0.9),
  ('odontología veterinaria', 'odontologia-veterinaria', 'veterinaria', 0.85),
  ('odontologia veterinaria', 'odontologia-veterinaria', 'veterinaria', 0.85),
  -- Peluquería canina
  ('peluquería canina', 'peluqueria-canina', 'peluqueria_canina', 0.95),
  ('peluqueria canina', 'peluqueria-canina', 'peluqueria_canina', 0.95),
  ('peluquero de perros', 'peluquero-de-perros', 'peluqueria_canina', 0.92),
  ('corte de perros', 'corte-de-perros', 'peluqueria_canina', 0.92),
  ('baño de perros', 'bano-de-perros', 'peluqueria_canina', 0.9),
  ('bano de perros', 'bano-de-perros', 'peluqueria_canina', 0.9),
  ('baño de gatos', 'bano-de-gatos', 'peluqueria_canina', 0.88),
  ('bano de gatos', 'bano-de-gatos', 'peluqueria_canina', 0.88),
  ('estética canina', 'estetica-canina', 'peluqueria_canina', 0.9),
  ('estetica canina', 'estetica-canina', 'peluqueria_canina', 0.9),
  ('grooming', 'grooming', 'peluqueria_canina', 0.88),
  ('corte de pelo perro', 'corte-de-pelo-perro', 'peluqueria_canina', 0.9),
  ('deslanado', 'deslanado', 'peluqueria_canina', 0.85),
  ('corte de uñas perro', 'corte-de-unas-perro', 'peluqueria_canina', 0.85),
  ('corte de unas perro', 'corte-de-unas-perro', 'peluqueria_canina', 0.85),
  -- Pensión y guardería
  ('pensión de mascotas', 'pension-de-mascotas', 'pension_guarderia', 0.95),
  ('pension de mascotas', 'pension-de-mascotas', 'pension_guarderia', 0.95),
  ('guardería de perros', 'guarderia-de-perros', 'pension_guarderia', 0.92),
  ('guarderia de perros', 'guarderia-de-perros', 'pension_guarderia', 0.92),
  ('guardería canina', 'guarderia-canina', 'pension_guarderia', 0.92),
  ('guarderia canina', 'guarderia-canina', 'pension_guarderia', 0.92),
  ('hotel para perros', 'hotel-para-perros', 'pension_guarderia', 0.9),
  ('hotel para mascotas', 'hotel-para-mascotas', 'pension_guarderia', 0.9),
  ('cuidado de mascotas', 'cuidado-de-mascotas', 'pension_guarderia', 0.88),
  ('alojamiento mascotas', 'alojamiento-mascotas', 'pension_guarderia', 0.9),
  ('dejar al perro', 'dejar-al-perro', 'pension_guarderia', 0.85),
  ('vacaciones mascota', 'vacaciones-mascota', 'pension_guarderia', 0.85),
  ('hospedaje de perros', 'hospedaje-de-perros', 'pension_guarderia', 0.88),
  -- Tienda de mascotas
  ('tienda de mascotas', 'tienda-de-mascotas', 'tienda_mascotas', 0.95),
  ('tienda mascotas', 'tienda-mascotas', 'tienda_mascotas', 0.95),
  ('pet shop', 'pet-shop', 'tienda_mascotas', 0.92),
  ('petshop', 'petshop', 'tienda_mascotas', 0.92),
  ('alimento para perros', 'alimento-para-perros', 'tienda_mascotas', 0.9),
  ('alimento para gatos', 'alimento-para-gatos', 'tienda_mascotas', 0.9),
  ('comida para perros', 'comida-para-perros', 'tienda_mascotas', 0.9),
  ('comida para gatos', 'comida-para-gatos', 'tienda_mascotas', 0.9),
  ('accesorios para mascotas', 'accesorios-para-mascotas', 'tienda_mascotas', 0.9),
  ('juguetes para perros', 'juguetes-para-perros', 'tienda_mascotas', 0.88),
  ('juguetes para gatos', 'juguetes-para-gatos', 'tienda_mascotas', 0.88),
  ('arena para gatos', 'arena-para-gatos', 'tienda_mascotas', 0.88),
  ('cama para perro', 'cama-para-perro', 'tienda_mascotas', 0.85),
  ('correa', 'correa', 'tienda_mascotas', 0.8),
  ('plato para perro', 'plato-para-perro', 'tienda_mascotas', 0.82),
  ('transporte para mascotas', 'transporte-para-mascotas', 'tienda_mascotas', 0.85),
  ('mascotas y veterinaria', 'mascotas-y-veterinaria', 'mascotas_veterinaria', 0.9),
  -- Adiestramiento
  ('adiestramiento', 'adiestramiento', 'adiestramiento', 1.0),
  ('adiestramiento canino', 'adiestramiento-canino', 'adiestramiento', 0.95),
  ('adiestrador', 'adiestrador', 'adiestramiento', 0.95),
  ('entrenamiento de perros', 'entrenamiento-de-perros', 'adiestramiento', 0.92),
  ('educación canina', 'educacion-canina', 'adiestramiento', 0.9),
  ('educacion canina', 'educacion-canina', 'adiestramiento', 0.9),
  ('obediencia canina', 'obediencia-canina', 'adiestramiento', 0.9),
  ('entrenar perro', 'entrenar-perro', 'adiestramiento', 0.88),
  ('corregir conducta perro', 'corregir-conducta-perro', 'adiestramiento', 0.88),
  ('perro desobediente', 'perro-desobediente', 'adiestramiento', 0.85),
  ('cachorro', 'cachorro', 'adiestramiento', 0.8),
  ('socialización canina', 'socializacion-canina', 'adiestramiento', 0.88),
  ('socializacion canina', 'socializacion-canina', 'adiestramiento', 0.88),
  -- Transporte de mascotas
  ('transporte de mascotas', 'transporte-de-mascotas', 'transporte_mascotas', 0.95),
  ('transporte mascotas', 'transporte-mascotas', 'transporte_mascotas', 0.95),
  ('taxi para mascotas', 'taxi-para-mascotas', 'transporte_mascotas', 0.9),
  ('traslado de mascotas', 'traslado-de-mascotas', 'transporte_mascotas', 0.9),
  ('llevar perro al vet', 'llevar-perro-al-vet', 'transporte_mascotas', 0.85),
  ('ambulancia mascotas', 'ambulancia-mascotas', 'transporte_mascotas', 0.88),
  -- Términos genéricos
  ('mascotas', 'mascotas', 'veterinaria', 0.8),
  ('perro', 'perro', 'veterinaria', 0.75),
  ('perros', 'perros', 'veterinaria', 0.75),
  ('gato', 'gato', 'veterinaria', 0.75),
  ('gatos', 'gatos', 'veterinaria', 0.75),
  ('animales', 'animales', 'veterinaria', 0.75),
  ('cuidado de perros', 'cuidado-de-perros', 'veterinaria', 0.85),
  ('cuidado de gatos', 'cuidado-de-gatos', 'veterinaria', 0.85)
) AS v(kw, norm, sub_slug, conf)
JOIN public.subcategorias s ON s.slug = v.sub_slug
ON CONFLICT (normalized_keyword) DO UPDATE SET
  keyword = EXCLUDED.keyword,
  subcategoria_id = EXCLUDED.subcategoria_id,
  confidence_default = EXCLUDED.confidence_default,
  updated_at = now();
