-- =============================================================================
-- Keywords v1 – Bloque 6: Comercio de barrio (~200)
-- =============================================================================

INSERT INTO public.keyword_to_subcategory_map (keyword, normalized_keyword, subcategoria_id, confidence_default, activo)
SELECT v.kw, v.norm, s.id, v.conf, true
FROM (VALUES
  -- Ferretería
  ('ferretería', 'ferreteria', 'ferreteria', 1.0),
  ('ferreteria', 'ferreteria', 'ferreteria', 1.0),
  ('ferretero', 'ferretero', 'ferreteria', 0.95),
  ('herramientas', 'herramientas', 'ferreteria', 0.9),
  ('tornillos', 'tornillos', 'ferreteria', 0.88),
  ('clavos', 'clavos', 'ferreteria', 0.88),
  ('pinturas', 'pinturas', 'ferreteria', 0.85),
  ('pegamento', 'pegamento', 'ferreteria', 0.85),
  ('taladro', 'taladro', 'ferreteria', 0.85),
  ('ferretería de barrio', 'ferreteria-de-barrio', 'ferreteria', 0.9),
  ('ferreteria de barrio', 'ferreteria-de-barrio', 'ferreteria', 0.9),
  ('ferretería y construcción', 'ferreteria-y-construccion', 'ferreteria_construccion', 0.92),
  ('ferreteria y construccion', 'ferreteria-y-construccion', 'ferreteria_construccion', 0.92),
  ('ferretería industrial', 'ferreteria-industrial', 'ferreteria_industrial', 0.92),
  ('ferreteria industrial', 'ferreteria-industrial', 'ferreteria_industrial', 0.92),
  -- Minimarket
  ('minimarket', 'minimarket', 'minimarket', 1.0),
  ('minimercado', 'minimercado', 'minimarket', 0.95),
  ('almacén', 'almacen', 'minimarket', 0.9),
  ('almacen', 'almacen', 'minimarket', 0.9),
  ('tienda de barrio', 'tienda-de-barrio', 'minimarket', 0.92),
  ('despensa', 'despensa', 'minimarket', 0.88),
  ('abarrotes', 'abarrotes', 'minimarket', 0.88),
  ('compras de barrio', 'compras-de-barrio', 'minimarket', 0.88),
  ('supermercado', 'supermercado', 'supermercado', 0.95),
  ('super', 'super', 'supermercado', 0.82),
  ('supermercado de barrio', 'supermercado-de-barrio', 'supermercado', 0.88),
  -- Ropa y moda
  ('ropa', 'ropa', 'ropa_moda', 0.9),
  ('moda', 'moda', 'ropa_moda', 0.9),
  ('ropa y moda', 'ropa-y-moda', 'ropa_moda', 0.95),
  ('tienda de ropa', 'tienda-de-ropa', 'ropa_moda', 0.9),
  ('vestuario', 'vestuario', 'ropa_moda', 0.88),
  ('prendas', 'prendas', 'ropa_moda', 0.85),
  ('calzado', 'calzado', 'calzado', 0.95),
  ('zapatos', 'zapatos', 'calzado', 0.92),
  ('zapatería', 'zapateria', 'calzado', 0.9),
  ('zapateria', 'zapateria', 'calzado', 0.9),
  ('zapatillas', 'zapatillas', 'calzado', 0.9),
  ('botas', 'botas', 'calzado', 0.85),
  -- Librería
  ('librería', 'libreria', 'libreria', 1.0),
  ('libreria', 'libreria', 'libreria', 1.0),
  ('libros', 'libros', 'libreria', 0.9),
  ('papelería', 'papeleria', 'libreria', 0.88),
  ('papeleria', 'papeleria', 'libreria', 0.88),
  ('útiles escolares', 'utiles-escolares', 'libreria', 0.9),
  ('utiles escolares', 'utiles-escolares', 'libreria', 0.9),
  ('útiles de oficina', 'utiles-de-oficina', 'libreria', 0.88),
  ('utiles de oficina', 'utiles-de-oficina', 'libreria', 0.88),
  ('cuadernos', 'cuadernos', 'libreria', 0.85),
  ('lápices', 'lapices', 'libreria', 0.85),
  ('lapices', 'lapices', 'libreria', 0.85),
  -- Juguetería
  ('juguetería', 'jugueteria', 'jugueteria', 1.0),
  ('jugueteria', 'jugueteria', 'jugueteria', 1.0),
  ('juguetes', 'juguetes', 'jugueteria', 0.95),
  ('juguete', 'juguete', 'jugueteria', 0.95),
  ('juegos', 'juegos', 'jugueteria', 0.85),
  ('regalos para niños', 'regalos-para-ninos', 'jugueteria', 0.88),
  ('regalos para ninos', 'regalos-para-ninos', 'jugueteria', 0.88),
  -- Bazar
  ('bazar', 'bazar', 'bazar', 1.0),
  ('bazar chino', 'bazar-chino', 'bazar', 0.9),
  ('todo a mil', 'todo-a-mil', 'bazar', 0.85),
  ('variedades', 'variedades', 'bazar', 0.88),
  ('artículos para el hogar', 'articulos-para-el-hogar', 'bazar', 0.88),
  ('articulos para el hogar', 'articulos-para-el-hogar', 'bazar', 0.88),
  -- Florería
  ('florería', 'floreria', 'floreria', 1.0),
  ('floreria', 'floreria', 'floreria', 1.0),
  ('florero', 'florero', 'floreria', 0.95),
  ('flores', 'flores', 'floreria', 0.92),
  ('ramos de flores', 'ramos-de-flores', 'floreria', 0.9),
  ('flores a domicilio', 'flores-a-domicilio', 'floreria', 0.9),
  ('arreglos florales', 'arreglos-florales', 'floreria', 0.9),
  ('flor para funeral', 'flor-para-funeral', 'floreria', 0.88),
  ('centro de mesa', 'centro-de-mesa', 'floreria', 0.85),
  -- Bicicletas
  ('bicicletas', 'bicicletas', 'bicicletas', 0.95),
  ('bicicleta', 'bicicleta', 'bicicletas', 0.95),
  ('bici', 'bici', 'bicicletas', 0.9),
  ('reparación de bicicletas', 'reparacion-de-bicicletas', 'bicicletas', 0.9),
  ('reparacion de bicicletas', 'reparacion-de-bicicletas', 'bicicletas', 0.9),
  ('bike', 'bike', 'bicicletas', 0.85),
  ('ciclo', 'ciclo', 'bicicletas', 0.82),
  -- Electrónica
  ('electrónica', 'electronica', 'electronica', 0.95),
  ('electronica', 'electronica', 'electronica', 0.95),
  ('tienda de electrónica', 'tienda-de-electronica', 'electronica', 0.9),
  ('tienda de electronica', 'tienda-de-electronica', 'electronica', 0.9),
  ('celulares', 'celulares', 'electronica', 0.85),
  ('audífonos', 'audifonos', 'electronica', 0.85),
  ('audifonos', 'audifonos', 'electronica', 0.85),
  ('cables', 'cables', 'electronica', 0.8),
  -- Artículos deportivos
  ('artículos deportivos', 'articulos-deportivos', 'articulos_deportivos', 0.95),
  ('articulos deportivos', 'articulos-deportivos', 'articulos_deportivos', 0.95),
  ('deportes', 'deportes', 'articulos_deportivos', 0.88),
  ('implementos deportivos', 'implementos-deportivos', 'articulos_deportivos', 0.9),
  ('ropa deportiva', 'ropa-deportiva', 'articulos_deportivos', 0.88),
  -- Bebidas y licores
  ('bebidas', 'bebidas', 'bebidas_licores', 0.9),
  ('licores', 'licores', 'bebidas_licores', 0.92),
  ('bebidas y licores', 'bebidas-y-licores', 'bebidas_licores', 0.95),
  ('licorería', 'licoreria', 'bebidas_licores', 0.9),
  ('licoreria', 'licoreria', 'bebidas_licores', 0.9),
  ('vino', 'vino', 'bebidas_licores', 0.88),
  ('cerveza', 'cerveza', 'bebidas_licores', 0.88),
  ('botillería', 'botilleria', 'bebidas_licores', 0.9),
  ('botilleria', 'botilleria', 'bebidas_licores', 0.9),
  -- Lácteos y quesos
  ('lácteos', 'lacteos', 'lacteos_quesos', 0.92),
  ('lacteos', 'lacteos', 'lacteos_quesos', 0.92),
  ('lácteos y quesos', 'lacteos-y-quesos', 'lacteos_quesos', 0.95),
  ('lacteos y quesos', 'lacteos-y-quesos', 'lacteos_quesos', 0.95),
  ('quesos', 'quesos', 'lacteos_quesos', 0.92),
  ('queso', 'queso', 'lacteos_quesos', 0.92),
  ('quesería', 'queseria', 'lacteos_quesos', 0.9),
  ('queseria', 'queseria', 'lacteos_quesos', 0.9),
  ('leche', 'leche', 'lacteos_quesos', 0.85),
  ('yogurt', 'yogurt', 'lacteos_quesos', 0.85),
  ('mantequilla', 'mantequilla', 'lacteos_quesos', 0.85),
  ('crema', 'crema', 'lacteos_quesos', 0.82)
) AS v(kw, norm, sub_slug, conf)
JOIN public.subcategorias s ON s.slug = v.sub_slug
ON CONFLICT (normalized_keyword) DO UPDATE SET
  keyword = EXCLUDED.keyword,
  subcategoria_id = EXCLUDED.subcategoria_id,
  confidence_default = EXCLUDED.confidence_default,
  updated_at = now();
