-- =============================================================================
-- Keywords v1 – Bloque 7: Tecnología (~200)
-- =============================================================================

INSERT INTO public.keyword_to_subcategory_map (keyword, normalized_keyword, subcategoria_id, confidence_default, activo)
SELECT v.kw, v.norm, s.id, v.conf, true
FROM (VALUES
  -- Reparación de celulares
  ('reparación de celulares', 'reparacion-de-celulares', 'reparacion_celulares', 0.95),
  ('reparacion de celulares', 'reparacion-de-celulares', 'reparacion_celulares', 0.95),
  ('reparación celular', 'reparacion-celular', 'reparacion_celulares', 0.95),
  ('reparacion celular', 'reparacion-celular', 'reparacion_celulares', 0.95),
  ('arreglo de celular', 'arreglo-de-celular', 'reparacion_celulares', 0.92),
  ('reparar celular', 'reparar-celular', 'reparacion_celulares', 0.92),
  ('reparar teléfono', 'reparar-telefono', 'reparacion_celulares', 0.9),
  ('reparar telefono', 'reparar-telefono', 'reparacion_celulares', 0.9),
  ('pantalla rota', 'pantalla-rota', 'reparacion_celulares', 0.9),
  ('cambio de pantalla', 'cambio-de-pantalla', 'reparacion_celulares', 0.9),
  ('display', 'display', 'reparacion_celulares', 0.85),
  ('batería celular', 'bateria-celular', 'reparacion_celulares', 0.88),
  ('bateria celular', 'bateria-celular', 'reparacion_celulares', 0.88),
  ('carga no enciende', 'carga-no-enciende', 'reparacion_celulares', 0.88),
  ('celular mojado', 'celular-mojado', 'reparacion_celulares', 0.9),
  ('celular con agua', 'celular-con-agua', 'reparacion_celulares', 0.88),
  ('iPhone reparación', 'iphone-reparacion', 'reparacion_celulares', 0.9),
  ('Samsung reparación', 'samsung-reparacion', 'reparacion_celulares', 0.88),
  ('Xiaomi reparación', 'xiaomi-reparacion', 'reparacion_celulares', 0.85),
  ('Huawei reparación', 'huawei-reparacion', 'reparacion_celulares', 0.85),
  ('desbloqueo', 'desbloqueo', 'reparacion_celulares', 0.85),
  ('liberación', 'liberacion', 'reparacion_celulares', 0.82),
  ('celular no prende', 'celular-no-prende', 'reparacion_celulares', 0.88),
  ('tactil no funciona', 'tactil-no-funciona', 'reparacion_celulares', 0.88),
  ('puerto de carga', 'puerto-de-carga', 'reparacion_celulares', 0.88),
  ('celular', 'celular', 'reparacion_celulares', 0.75),
  ('celulares', 'celulares', 'reparacion_celulares', 0.75),
  ('smartphone', 'smartphone', 'reparacion_celulares', 0.85),
  -- Reparación de computadores
  ('reparación de computadores', 'reparacion-de-computadores', 'reparacion_computadores', 0.95),
  ('reparacion de computadores', 'reparacion-de-computadores', 'reparacion_computadores', 0.95),
  ('reparación computador', 'reparacion-computador', 'reparacion_computadores', 0.95),
  ('reparacion computador', 'reparacion-computador', 'reparacion_computadores', 0.95),
  ('arreglo de computador', 'arreglo-de-computador', 'reparacion_computadores', 0.92),
  ('reparar PC', 'reparar-pc', 'reparacion_computadores', 0.9),
  ('reparar computador', 'reparar-computador', 'reparacion_computadores', 0.92),
  ('formateo', 'formateo', 'reparacion_computadores', 0.88),
  ('formatear PC', 'formatear-pc', 'reparacion_computadores', 0.9),
  ('computador lento', 'computador-lento', 'reparacion_computadores', 0.88),
  ('virus', 'virus', 'reparacion_computadores', 0.85),
  ('eliminar virus', 'eliminar-virus', 'reparacion_computadores', 0.9),
  ('mantención de PC', 'mantencion-de-pc', 'reparacion_computadores', 0.88),
  ('mantencion de pc', 'mantencion-de-pc', 'reparacion_computadores', 0.88),
  ('cambio de disco', 'cambio-de-disco', 'reparacion_computadores', 0.88),
  ('SSD', 'ssd', 'reparacion_computadores', 0.82),
  ('RAM', 'ram', 'reparacion_computadores', 0.82),
  ('reparación de notebooks', 'reparacion-de-notebooks', 'reparacion_notebooks', 0.95),
  ('reparacion de notebooks', 'reparacion-de-notebooks', 'reparacion_notebooks', 0.95),
  ('reparar notebook', 'reparar-notebook', 'reparacion_notebooks', 0.92),
  ('notebook no enciende', 'notebook-no-enciende', 'reparacion_notebooks', 0.9),
  ('laptop', 'laptop', 'reparacion_notebooks', 0.88),
  ('portátil', 'portatil', 'reparacion_notebooks', 0.88),
  ('portatil', 'portatil', 'reparacion_notebooks', 0.88),
  -- Instalación de redes
  ('instalación de redes', 'instalacion-de-redes', 'instalacion_redes', 0.95),
  ('instalacion de redes', 'instalacion-de-redes', 'instalacion_redes', 0.95),
  ('redes', 'redes', 'instalacion_redes', 0.88),
  ('WiFi', 'wifi', 'instalacion_redes', 0.9),
  ('wifi', 'wifi', 'instalacion_redes', 0.9),
  ('instalación WiFi', 'instalacion-wifi', 'instalacion_redes', 0.92),
  ('instalacion wifi', 'instalacion-wifi', 'instalacion_redes', 0.92),
  ('router', 'router', 'instalacion_redes', 0.85),
  ('internet', 'internet', 'instalacion_redes', 0.82),
  ('fibra óptica', 'fibra-optica', 'instalacion_redes', 0.9),
  ('fibra optica', 'fibra-optica', 'instalacion_redes', 0.9),
  ('cableado', 'cableado', 'instalacion_redes', 0.88),
  ('red LAN', 'red-lan', 'instalacion_redes', 0.88),
  ('red lan', 'red-lan', 'instalacion_redes', 0.88),
  ('repetidor', 'repetidor', 'instalacion_redes', 0.85),
  ('señal débil', 'senal-debil', 'instalacion_redes', 0.85),
  ('senal debil', 'senal-debil', 'instalacion_redes', 0.85),
  -- Desarrollo de software
  ('desarrollo de software', 'desarrollo-de-software', 'desarrollo_software', 0.95),
  ('desarrollo software', 'desarrollo-software', 'desarrollo_software', 0.95),
  ('programación', 'programacion', 'desarrollo_software', 0.9),
  ('programacion', 'programacion', 'desarrollo_software', 0.9),
  ('programador', 'programador', 'desarrollo_software', 0.9),
  ('desarrollador', 'desarrollador', 'desarrollo_software', 0.9),
  ('app', 'app', 'desarrollo_software', 0.85),
  ('aplicación móvil', 'aplicacion-movil', 'desarrollo_software', 0.9),
  ('aplicacion movil', 'aplicacion-movil', 'desarrollo_software', 0.9),
  ('página web', 'pagina-web', 'desarrollo_software', 0.88),
  ('pagina web', 'pagina-web', 'desarrollo_software', 0.88),
  ('sitio web', 'sitio-web', 'desarrollo_software', 0.88),
  ('sistema a medida', 'sistema-a-medida', 'desarrollo_software', 0.9),
  ('software a medida', 'software-a-medida', 'desarrollo_software', 0.9),
  ('ti', 'ti', 'desarrollo_software', 0.75),
  ('tecnología', 'tecnologia', 'desarrollo_software', 0.8),
  ('tecnologia', 'tecnologia', 'desarrollo_software', 0.8),
  -- Impresión y diseño
  ('impresión', 'impresion', 'impresion_diseno', 0.9),
  ('impresion', 'impresion', 'impresion_diseno', 0.9),
  ('impresión y diseño', 'impresion-y-diseno', 'impresion_diseno', 0.95),
  ('impresion y diseno', 'impresion-y-diseno', 'impresion_diseno', 0.95),
  ('imprenta', 'imprenta', 'impresion_diseno', 0.92),
  ('copias', 'copias', 'impresion_diseno', 0.88),
  ('fotocopias', 'fotocopias', 'impresion_diseno', 0.9),
  ('plotter', 'plotter', 'impresion_diseno', 0.85),
  ('diseño gráfico', 'diseno-grafico', 'impresion_diseno', 0.88),
  ('diseno grafico', 'diseno-grafico', 'impresion_diseno', 0.88),
  ('volantes', 'volantes', 'impresion_diseno', 0.88),
  ('tarjetas de presentación', 'tarjetas-de-presentacion', 'impresion_diseno', 0.9),
  ('tarjetas de presentacion', 'tarjetas-de-presentacion', 'impresion_diseno', 0.9),
  ('banner', 'banner', 'impresion_diseno', 0.85),
  ('vinilo', 'vinilo', 'impresion_diseno', 0.85),
  ('lona', 'lona', 'impresion_diseno', 0.85),
  ('plotear', 'plotear', 'impresion_diseno', 0.82),
  -- Antenas y televisión
  ('antenas', 'antenas', 'antenas_television', 0.95),
  ('antena', 'antena', 'antenas_television', 0.95),
  ('antenas y televisión', 'antenas-y-television', 'antenas_television', 0.95),
  ('antenas y television', 'antenas-y-television', 'antenas_television', 0.95),
  ('televisión', 'television', 'antenas_television', 0.88),
  ('television', 'television', 'antenas_television', 0.88),
  ('instalación de antena', 'instalacion-de-antena', 'antenas_television', 0.92),
  ('instalacion de antena', 'instalacion-de-antena', 'antenas_television', 0.92),
  ('señal TV', 'senal-tv', 'antenas_television', 0.9),
  ('senal tv', 'senal-tv', 'antenas_television', 0.9),
  ('televisor no tiene señal', 'televisor-no-tiene-senal', 'antenas_television', 0.88),
  ('televisor no tiene senal', 'televisor-no-tiene-senal', 'antenas_television', 0.88),
  ('antena digital', 'antena-digital', 'antenas_television', 0.9),
  ('TDT', 'tdt', 'antenas_television', 0.85),
  ('tdt', 'tdt', 'antenas_television', 0.85),
  ('cable TV', 'cable-tv', 'antenas_television', 0.85),
  ('cable tv', 'cable-tv', 'antenas_television', 0.85)
) AS v(kw, norm, sub_slug, conf)
JOIN public.subcategorias s ON s.slug = v.sub_slug
ON CONFLICT (normalized_keyword) DO UPDATE SET
  keyword = EXCLUDED.keyword,
  subcategoria_id = EXCLUDED.subcategoria_id,
  confidence_default = EXCLUDED.confidence_default,
  updated_at = now();
