-- =============================================================================
-- Keywords v1 – Bloque 8: Salud (~200)
-- =============================================================================

INSERT INTO public.keyword_to_subcategory_map (keyword, normalized_keyword, subcategoria_id, confidence_default, activo)
SELECT v.kw, v.norm, s.id, v.conf, true
FROM (VALUES
  -- Odontología
  ('odontología', 'odontologia', 'odontologia', 1.0),
  ('odontologia', 'odontologia', 'odontologia', 1.0),
  ('dentista', 'dentista', 'odontologia', 0.95),
  ('dentistas', 'dentistas', 'odontologia', 0.95),
  ('clínica dental', 'clinica-dental', 'odontologia', 0.92),
  ('clinica dental', 'clinica-dental', 'odontologia', 0.92),
  ('odontólogo', 'odontologo', 'odontologia', 0.95),
  ('odontologo', 'odontologo', 'odontologia', 0.95),
  ('blanqueamiento dental', 'blanqueamiento-dental', 'odontologia', 0.9),
  ('limpieza dental', 'limpieza-dental', 'odontologia', 0.9),
  ('ortodoncia', 'ortodoncia', 'odontologia', 0.9),
  ('brackets', 'brackets', 'odontologia', 0.88),
  ('implante dental', 'implante-dental', 'odontologia', 0.9),
  ('implantes', 'implantes', 'odontologia', 0.88),
  ('endodoncia', 'endodoncia', 'odontologia', 0.88),
  ('conducto', 'conducto', 'odontologia', 0.85),
  ('extracción de muela', 'extraccion-de-muela', 'odontologia', 0.88),
  ('extraccion de muela', 'extraccion-de-muela', 'odontologia', 0.88),
  ('dolor de muela', 'dolor-de-muela', 'odontologia', 0.88),
  ('caries', 'caries', 'odontologia', 0.88),
  ('dientes', 'dientes', 'odontologia', 0.8),
  -- Kinesiología
  ('kinesiología', 'kinesiologia', 'kinesiologia', 1.0),
  ('kinesiologia', 'kinesiologia', 'kinesiologia', 1.0),
  ('kinesiólogo', 'kinesiologo', 'kinesiologia', 0.95),
  ('kinesiologo', 'kinesiologo', 'kinesiologia', 0.95),
  ('kine', 'kine', 'kinesiologia', 0.9),
  ('fisioterapia', 'fisioterapia', 'kinesiologia', 0.92),
  ('rehabilitación', 'rehabilitacion', 'kinesiologia', 0.9),
  ('rehabilitacion', 'rehabilitacion', 'kinesiologia', 0.9),
  ('lesión deportiva', 'lesion-deportiva', 'kinesiologia', 0.9),
  ('lesion deportiva', 'lesion-deportiva', 'kinesiologia', 0.9),
  ('esguince', 'esguince', 'kinesiologia', 0.88),
  ('lumbago', 'lumbago', 'kinesiologia', 0.88),
  ('ciática', 'ciatica', 'kinesiologia', 0.88),
  ('ciatica', 'ciatica', 'kinesiologia', 0.88),
  ('tendinitis', 'tendinitis', 'kinesiologia', 0.88),
  ('contractura', 'contractura', 'kinesiologia', 0.88),
  ('masaje kinesiológico', 'masaje-kinesiologico', 'kinesiologia', 0.9),
  ('masaje kinesiologico', 'masaje-kinesiologico', 'kinesiologia', 0.9),
  ('kinesiología a domicilio', 'kinesiologia-a-domicilio', 'kinesiologia', 0.92),
  ('kinesiologia a domicilio', 'kinesiologia-a-domicilio', 'kinesiologia', 0.92),
  -- Nutrición
  ('nutrición', 'nutricion', 'nutricion', 1.0),
  ('nutricion', 'nutricion', 'nutricion', 1.0),
  ('nutricionista', 'nutricionista', 'nutricion', 0.95),
  ('nutriólogo', 'nutriologo', 'nutricion', 0.95),
  ('nutriologo', 'nutriologo', 'nutricion', 0.95),
  ('dieta', 'dieta', 'nutricion', 0.88),
  ('plan alimenticio', 'plan-alimenticio', 'nutricion', 0.9),
  ('bajar de peso', 'bajar-de-peso', 'nutricion', 0.88),
  ('subir de peso', 'subir-de-peso', 'nutricion', 0.85),
  ('alimentación saludable', 'alimentacion-saludable', 'nutricion', 0.9),
  ('alimentacion saludable', 'alimentacion-saludable', 'nutricion', 0.9),
  ('consultorio nutricional', 'consultorio-nutricional', 'nutricion', 0.9),
  -- Psicología
  ('psicología', 'psicologia', 'psicologia', 1.0),
  ('psicologia', 'psicologia', 'psicologia', 1.0),
  ('psicólogo', 'psicologo', 'psicologia', 0.95),
  ('psicologo', 'psicologo', 'psicologia', 0.95),
  ('psicóloga', 'psicologa', 'psicologia', 0.95),
  ('psicologa', 'psicologa', 'psicologia', 0.95),
  ('terapia', 'terapia', 'psicologia', 0.88),
  ('terapia psicológica', 'terapia-psicologica', 'psicologia', 0.92),
  ('terapia psicologica', 'terapia-psicologica', 'psicologia', 0.92),
  ('consulta psicológica', 'consulta-psicologica', 'psicologia', 0.9),
  ('consulta psicologica', 'consulta-psicologica', 'psicologia', 0.9),
  ('salud mental', 'salud-mental', 'psicologia', 0.9),
  ('ansiedad', 'ansiedad', 'psicologia', 0.85),
  ('depresión', 'depresion', 'psicologia', 0.85),
  ('depresion', 'depresion', 'psicologia', 0.85),
  ('psicólogo infantil', 'psicologo-infantil', 'psicologia', 0.9),
  ('psicologo infantil', 'psicologo-infantil', 'psicologia', 0.9),
  ('psicólogo a domicilio', 'psicologo-a-domicilio', 'psicologia', 0.88),
  ('psicologo a domicilio', 'psicologo-a-domicilio', 'psicologia', 0.88),
  -- Fonoaudiología
  ('fonoaudiología', 'fonoaudiologia', 'fonoaudiologia', 1.0),
  ('fonoaudiologia', 'fonoaudiologia', 'fonoaudiologia', 1.0),
  ('fonoaudiólogo', 'fonoaudiologo', 'fonoaudiologia', 0.95),
  ('fonoaudiologo', 'fonoaudiologo', 'fonoaudiologia', 0.95),
  ('fono', 'fono', 'fonoaudiologia', 0.9),
  ('trastorno del lenguaje', 'trastorno-del-lenguaje', 'fonoaudiologia', 0.9),
  ('tartamudez', 'tartamudez', 'fonoaudiologia', 0.88),
  ('dislalia', 'dislalia', 'fonoaudiologia', 0.85),
  ('terapia del habla', 'terapia-del-habla', 'fonoaudiologia', 0.9),
  ('fono infantil', 'fono-infantil', 'fonoaudiologia', 0.9),
  -- Óptica
  ('óptica', 'optica', 'optica', 1.0),
  ('optica', 'optica', 'optica', 1.0),
  ('óptico', 'optico', 'optica', 0.95),
  ('optico', 'optico', 'optica', 0.95),
  ('lentes', 'lentes', 'optica', 0.92),
  ('antiparras', 'antiparras', 'optica', 0.88),
  ('lentes ópticos', 'lentes-opticos', 'optica', 0.9),
  ('lentes opticos', 'lentes-opticos', 'optica', 0.9),
  ('armazón', 'armazon', 'optica', 0.88),
  ('armazon', 'armazon', 'optica', 0.88),
  ('graduación de vista', 'graduacion-de-vista', 'optica', 0.92),
  ('graduacion de vista', 'graduacion-de-vista', 'optica', 0.92),
  ('miopía', 'miopia', 'optica', 0.88),
  ('miopia', 'miopia', 'optica', 0.88),
  ('astigmatismo', 'astigmatismo', 'optica', 0.88),
  ('lentes de contacto', 'lentes-de-contacto', 'optica', 0.9),
  ('lentes de sol', 'lentes-de-sol', 'optica', 0.85),
  -- Farmacia
  ('farmacia', 'farmacia', 'farmacia', 1.0),
  ('botica', 'botica', 'farmacia', 0.92),
  ('químico farmacéutico', 'quimico-farmaceutico', 'farmacia', 0.9),
  ('quimico farmaceutico', 'quimico-farmaceutico', 'farmacia', 0.9),
  ('medicamentos', 'medicamentos', 'farmacia', 0.9),
  ('remedio', 'remedio', 'farmacia', 0.88),
  ('remedios', 'remedios', 'farmacia', 0.88),
  ('farmacia de turno', 'farmacia-de-turno', 'farmacia', 0.9),
  ('farmacia 24 horas', 'farmacia-24-horas', 'farmacia', 0.88),
  ('receta', 'receta', 'farmacia', 0.8),
  -- Podología
  ('podología', 'podologia', 'podologia', 1.0),
  ('podologia', 'podologia', 'podologia', 1.0),
  ('podólogo', 'podologo', 'podologia', 0.95),
  ('podologo', 'podologo', 'podologia', 0.95),
  ('pie', 'pie', 'podologia', 0.8),
  ('pies', 'pies', 'podologia', 0.8),
  ('callos', 'callos', 'podologia', 0.88),
  ('uña encarnada', 'una-encarnada', 'podologia', 0.9),
  ('una encarnada', 'una-encarnada', 'podologia', 0.9),
  ('hongos en los pies', 'hongos-en-los-pies', 'podologia', 0.88),
  ('plantillas', 'plantillas', 'podologia', 0.88),
  ('quiropodía', 'quiropodia', 'podologia', 0.9),
  ('quiropodia', 'quiropodia', 'podologia', 0.9),
  -- Terapia ocupacional
  ('terapia ocupacional', 'terapia-ocupacional', 'terapia_ocupacional', 0.95),
  ('terapeuta ocupacional', 'terapeuta-ocupacional', 'terapia_ocupacional', 0.95),
  ('TO', 'to', 'terapia_ocupacional', 0.85),
  ('rehabilitación ocupacional', 'rehabilitacion-ocupacional', 'terapia_ocupacional', 0.9),
  ('rehabilitacion ocupacional', 'rehabilitacion-ocupacional', 'terapia_ocupacional', 0.9),
  -- Enfermería a domicilio
  ('enfermería a domicilio', 'enfermeria-a-domicilio', 'enfermeria_domicilio', 0.95),
  ('enfermeria a domicilio', 'enfermeria-a-domicilio', 'enfermeria_domicilio', 0.95),
  ('enfermera a domicilio', 'enfermera-a-domicilio', 'enfermeria_domicilio', 0.95),
  ('cuidados domiciliarios', 'cuidados-domiciliarios', 'enfermeria_domicilio', 0.9),
  ('inyecciones a domicilio', 'inyecciones-a-domicilio', 'enfermeria_domicilio', 0.9),
  ('curaciones', 'curaciones', 'enfermeria_domicilio', 0.88),
  ('toma de muestra', 'toma-de-muestra', 'enfermeria_domicilio', 0.88),
  -- Medicina general y terapias
  ('medicina general', 'medicina-general', 'medicina_general', 0.95),
  ('médico', 'medico', 'medicina_general', 0.9),
  ('medico', 'medico', 'medicina_general', 0.9),
  ('doctor', 'doctor', 'medicina_general', 0.9),
  ('consulta médica', 'consulta-medica', 'medicina_general', 0.9),
  ('consulta medica', 'consulta-medica', 'medicina_general', 0.9),
  ('terapias alternativas', 'terapias-alternativas', 'terapias_alternativas', 0.92),
  ('terapias alternativas', 'terapias-alternativas', 'terapias_alternativas', 0.92),
  ('medicina alternativa', 'medicina-alternativa', 'terapias_alternativas', 0.9),
  ('acupuntura', 'acupuntura', 'terapias_alternativas', 0.9),
  ('reiki', 'reiki', 'terapias_alternativas', 0.88),
  ('florales', 'florales', 'terapias_alternativas', 0.85),
  ('naturopatía', 'naturopatia', 'terapias_alternativas', 0.88),
  ('naturopatia', 'naturopatia', 'terapias_alternativas', 0.88)
) AS v(kw, norm, sub_slug, conf)
JOIN public.subcategorias s ON s.slug = v.sub_slug
ON CONFLICT (normalized_keyword) DO UPDATE SET
  keyword = EXCLUDED.keyword,
  subcategoria_id = EXCLUDED.subcategoria_id,
  confidence_default = EXCLUDED.confidence_default,
  updated_at = now();
