-- =============================================================================
-- Keywords v1 – Bloque 9: Educación (~200)
-- =============================================================================

INSERT INTO public.keyword_to_subcategory_map (keyword, normalized_keyword, subcategoria_id, confidence_default, activo)
SELECT v.kw, v.norm, s.id, v.conf, true
FROM (VALUES
  -- Clases y capacitación
  ('clases', 'clases', 'clases', 1.0),
  ('clases particulares', 'clases-particulares', 'clases', 0.95),
  ('clase particular', 'clase-particular', 'clases', 0.95),
  ('profesor particular', 'profesor-particular', 'clases', 0.92),
  ('profesora particular', 'profesora-particular', 'clases', 0.92),
  ('clases a domicilio', 'clases-a-domicilio', 'clases', 0.92),
  ('refuerzo', 'refuerzo', 'clases', 0.88),
  ('refuerzo escolar', 'refuerzo-escolar', 'reforzamiento_escolar', 0.92),
  ('reforzamiento', 'reforzamiento', 'reforzamiento_escolar', 0.9),
  ('reforzamiento escolar', 'reforzamiento-escolar', 'reforzamiento_escolar', 0.95),
  ('tutor', 'tutor', 'clases', 0.9),
  ('tutora', 'tutora', 'clases', 0.9),
  ('capacitación', 'capacitacion', 'clases', 0.9),
  ('capacitacion', 'capacitacion', 'clases', 0.9),
  ('capacitación empresarial', 'capacitacion-empresarial', 'capacitacion_empresarial', 0.95),
  ('capacitacion empresarial', 'capacitacion-empresarial', 'capacitacion_empresarial', 0.95),
  ('cursos', 'cursos', 'clases', 0.85),
  ('curso', 'curso', 'clases', 0.85),
  ('cursos técnicos', 'cursos-tecnicos', 'cursos_tecnicos', 0.95),
  ('cursos tecnicos', 'cursos-tecnicos', 'cursos_tecnicos', 0.95),
  ('cursos online', 'cursos-online', 'cursos_online', 0.95),
  ('clases online', 'clases-online', 'cursos_online', 0.92),
  ('educación', 'educacion', 'clases', 0.8),
  ('educacion', 'educacion', 'clases', 0.8),
  -- Idiomas
  ('idiomas', 'idiomas', 'idiomas', 1.0),
  ('inglés', 'ingles', 'idiomas', 0.95),
  ('ingles', 'ingles', 'idiomas', 0.95),
  ('clases de inglés', 'clases-de-ingles', 'idiomas', 0.95),
  ('clases de ingles', 'clases-de-ingles', 'idiomas', 0.95),
  ('profesor de inglés', 'profesor-de-ingles', 'idiomas', 0.92),
  ('profesor de ingles', 'profesor-de-ingles', 'idiomas', 0.92),
  ('inglés para niños', 'ingles-para-ninos', 'idiomas', 0.9),
  ('ingles para ninos', 'ingles-para-ninos', 'idiomas', 0.9),
  ('inglés empresarial', 'ingles-empresarial', 'idiomas', 0.9),
  ('ingles empresarial', 'ingles-empresarial', 'idiomas', 0.9),
  ('traducción', 'traduccion', 'idiomas', 0.85),
  ('traduccion', 'traduccion', 'idiomas', 0.85),
  ('portugués', 'portugues', 'idiomas', 0.88),
  ('portugues', 'portugues', 'idiomas', 0.88),
  ('francés', 'frances', 'idiomas', 0.88),
  ('frances', 'frances', 'idiomas', 0.88),
  ('alemán', 'aleman', 'idiomas', 0.85),
  ('aleman', 'aleman', 'idiomas', 0.85),
  ('chino', 'chino', 'idiomas', 0.85),
  ('idioma', 'idioma', 'idiomas', 0.82),
  -- Música
  ('música', 'musica', 'musica', 1.0),
  ('musica', 'musica', 'musica', 1.0),
  ('clases de música', 'clases-de-musica', 'musica', 0.95),
  ('clases de musica', 'clases-de-musica', 'musica', 0.95),
  ('guitarra', 'guitarra', 'guitarra_instrumentos', 0.95),
  ('clases de guitarra', 'clases-de-guitarra', 'guitarra_instrumentos', 0.95),
  ('guitarra y instrumentos', 'guitarra-y-instrumentos', 'guitarra_instrumentos', 0.95),
  ('piano', 'piano', 'guitarra_instrumentos', 0.92),
  ('clases de piano', 'clases-de-piano', 'guitarra_instrumentos', 0.92),
  ('batería', 'bateria', 'guitarra_instrumentos', 0.9),
  ('bateria', 'bateria', 'guitarra_instrumentos', 0.9),
  ('clases de batería', 'clases-de-bateria', 'guitarra_instrumentos', 0.9),
  ('clases de bateria', 'clases-de-bateria', 'guitarra_instrumentos', 0.9),
  ('violín', 'violin', 'guitarra_instrumentos', 0.88),
  ('violin', 'violin', 'guitarra_instrumentos', 0.88),
  ('saxofón', 'saxofon', 'guitarra_instrumentos', 0.88),
  ('saxofon', 'saxofon', 'guitarra_instrumentos', 0.88),
  ('flauta', 'flauta', 'guitarra_instrumentos', 0.88),
  ('instrumentos', 'instrumentos', 'guitarra_instrumentos', 0.85),
  ('profesor de música', 'profesor-de-musica', 'musica', 0.92),
  ('profesor de musica', 'profesor-de-musica', 'musica', 0.92),
  ('canto', 'canto', 'musica', 0.9),
  ('clases de canto', 'clases-de-canto', 'musica', 0.9),
  -- Preuniversitario
  ('preuniversitario', 'preuniversitario', 'preuniversitario', 1.0),
  ('preu', 'preu', 'preuniversitario', 0.95),
  ('preparación PSU', 'preparacion-psu', 'preuniversitario', 0.92),
  ('preparacion psu', 'preparacion-psu', 'preuniversitario', 0.92),
  ('PSU', 'psu', 'preuniversitario', 0.9),
  ('psu', 'psu', 'preuniversitario', 0.9),
  ('preparación PAES', 'preparacion-paes', 'preuniversitario', 0.92),
  ('preparacion paes', 'preparacion-paes', 'preuniversitario', 0.92),
  ('PAES', 'paes', 'preuniversitario', 0.9),
  ('paes', 'paes', 'preuniversitario', 0.9),
  ('prueba de transición', 'prueba-de-transicion', 'preuniversitario', 0.88),
  ('prueba de transicion', 'prueba-de-transicion', 'preuniversitario', 0.88),
  ('matemáticas PSU', 'matematicas-psu', 'preuniversitario', 0.9),
  ('matematicas psu', 'matematicas-psu', 'preuniversitario', 0.9),
  ('lenguaje PSU', 'lenguaje-psu', 'preuniversitario', 0.9),
  ('lenguaje psu', 'lenguaje-psu', 'preuniversitario', 0.9),
  ('ensayo PSU', 'ensayo-psu', 'preuniversitario', 0.88),
  ('ensayo psu', 'ensayo-psu', 'preuniversitario', 0.88),
  -- Computación
  ('computación', 'computacion', 'computacion', 1.0),
  ('computacion', 'computacion', 'computacion', 1.0),
  ('clases de computación', 'clases-de-computacion', 'computacion', 0.95),
  ('clases de computacion', 'clases-de-computacion', 'computacion', 0.95),
  ('computación para adultos', 'computacion-para-adultos', 'computacion', 0.9),
  ('computacion para adultos', 'computacion-para-adultos', 'computacion', 0.9),
  ('excel', 'excel', 'computacion', 0.88),
  ('word', 'word', 'computacion', 0.88),
  ('power point', 'power-point', 'computacion', 0.85),
  ('powerpoint', 'powerpoint', 'computacion', 0.85),
  ('internet para adultos', 'internet-para-adultos', 'computacion', 0.88),
  ('celular para adultos', 'celular-para-adultos', 'computacion', 0.85),
  ('alfabetización digital', 'alfabetizacion-digital', 'computacion', 0.9),
  ('alfabetizacion digital', 'alfabetizacion-digital', 'computacion', 0.9),
  -- Danza
  ('danza', 'danza', 'danza', 1.0),
  ('clases de danza', 'clases-de-danza', 'danza', 0.95),
  ('baile', 'baile', 'danza', 0.92),
  ('clases de baile', 'clases-de-baile', 'danza', 0.92),
  ('academia de baile', 'academia-de-baile', 'danza', 0.9),
  ('salsa', 'salsa', 'danza', 0.88),
  ('bachata', 'bachata', 'danza', 0.88),
  ('zumba', 'zumba', 'danza', 0.88),
  ('ballet', 'ballet', 'danza', 0.9),
  ('danza contemporánea', 'danza-contemporanea', 'danza', 0.88),
  ('danza contemporanea', 'danza-contemporanea', 'danza', 0.88),
  ('hip hop', 'hip-hop', 'danza', 0.88),
  ('reguetón', 'regeton', 'danza', 0.85),
  ('regeton', 'regeton', 'danza', 0.85),
  -- Arte y manualidades
  ('arte y manualidades', 'arte-y-manualidades', 'arte_manualidades', 0.95),
  ('arte y manualidades', 'arte-y-manualidades', 'arte_manualidades', 0.95),
  ('manualidades', 'manualidades', 'arte_manualidades', 0.92),
  ('talleres', 'talleres', 'arte_manualidades', 0.88),
  ('taller de arte', 'taller-de-arte', 'arte_manualidades', 0.9),
  ('pintura para niños', 'pintura-para-ninos', 'arte_manualidades', 0.88),
  ('pintura para ninos', 'pintura-para-ninos', 'arte_manualidades', 0.88),
  ('dibujo', 'dibujo', 'arte_manualidades', 0.88),
  ('clases de dibujo', 'clases-de-dibujo', 'arte_manualidades', 0.9),
  ('cerámica', 'ceramica', 'arte_manualidades', 0.88),
  ('ceramica', 'ceramica', 'arte_manualidades', 0.88),
  ('taller de cerámica', 'taller-de-ceramica', 'arte_manualidades', 0.9),
  ('taller de ceramica', 'taller-de-ceramica', 'arte_manualidades', 0.9),
  ('manualidades para niños', 'manualidades-para-ninos', 'arte_manualidades', 0.88),
  ('manualidades para ninos', 'manualidades-para-ninos', 'arte_manualidades', 0.88),
  ('talleres creativos', 'talleres-creativos', 'talleres_creativos', 0.9)
) AS v(kw, norm, sub_slug, conf)
JOIN public.subcategorias s ON s.slug = v.sub_slug
ON CONFLICT (normalized_keyword) DO UPDATE SET
  keyword = EXCLUDED.keyword,
  subcategoria_id = EXCLUDED.subcategoria_id,
  confidence_default = EXCLUDED.confidence_default,
  updated_at = now();
