-- =============================================================================
-- Keywords v1 – Bloque 10: Eventos (~200)
-- =============================================================================

INSERT INTO public.keyword_to_subcategory_map (keyword, normalized_keyword, subcategoria_id, confidence_default, activo)
SELECT v.kw, v.norm, s.id, v.conf, true
FROM (VALUES
  -- Salón de eventos / fiestas
  ('salón de eventos', 'salon-de-eventos', 'salon_eventos', 0.95),
  ('salon de eventos', 'salon-de-eventos', 'salon_eventos', 0.95),
  ('salón de fiestas', 'salon-de-fiestas', 'salon_fiestas', 0.95),
  ('salon de fiestas', 'salon-de-fiestas', 'salon_fiestas', 0.95),
  ('salón para eventos', 'salon-para-eventos', 'salon_eventos', 0.95),
  ('salon para eventos', 'salon-para-eventos', 'salon_eventos', 0.95),
  ('arriendo de salón', 'arriendo-de-salon', 'salon_eventos', 0.92),
  ('arriendo de salon', 'arriendo-de-salon', 'salon_eventos', 0.92),
  ('salón matrimonio', 'salon-matrimonio', 'salon_eventos', 0.9),
  ('salon matrimonio', 'salon-matrimonio', 'salon_eventos', 0.9),
  ('salón cumpleaños', 'salon-cumpleanos', 'salon_eventos', 0.9),
  ('salon cumpleanos', 'salon-cumpleanos', 'salon_eventos', 0.9),
  ('eventos', 'eventos', 'salon_eventos', 0.85),
  ('fiestas', 'fiestas', 'salon_fiestas', 0.9),
  ('fiesta', 'fiesta', 'salon_fiestas', 0.9),
  ('organización de eventos', 'organizacion-de-eventos', 'organizacion_eventos', 0.95),
  ('organizacion de eventos', 'organizacion-de-eventos', 'organizacion_eventos', 0.95),
  ('organizador de eventos', 'organizador-de-eventos', 'organizacion_eventos', 0.92),
  ('coordinación de eventos', 'coordinacion-de-eventos', 'organizacion_eventos', 0.9),
  ('coordinacion de eventos', 'coordinacion-de-eventos', 'organizacion_eventos', 0.9),
  ('eventos corporativos', 'eventos-corporativos', 'organizacion_eventos', 0.9),
  ('matrimonio', 'matrimonio', 'salon_eventos', 0.88),
  ('boda', 'boda', 'salon_eventos', 0.9),
  ('bodas', 'bodas', 'salon_eventos', 0.9),
  ('cumpleaños', 'cumpleanos', 'salon_fiestas', 0.9),
  ('cumpleanos', 'cumpleanos', 'salon_fiestas', 0.9),
  ('cumpleaños infantil', 'cumpleanos-infantil', 'salon_fiestas', 0.9),
  ('cumpleanos infantil', 'cumpleanos-infantil', 'salon_fiestas', 0.9),
  ('bautizo', 'bautizo', 'salon_eventos', 0.88),
  ('primera comunión', 'primera-comunion', 'salon_eventos', 0.88),
  ('primera comunion', 'primera-comunion', 'salon_eventos', 0.88),
  ('graduación', 'graduacion', 'salon_eventos', 0.88),
  ('graduacion', 'graduacion', 'salon_eventos', 0.88),
  ('aniversario', 'aniversario', 'salon_eventos', 0.85),
  -- Catering
  ('catering', 'catering', 'catering', 1.0),
  ('servicio de catering', 'servicio-de-catering', 'catering', 0.95),
  ('catering para eventos', 'catering-para-eventos', 'catering', 0.95),
  ('comida para eventos', 'comida-para-eventos', 'catering', 0.92),
  ('banquete', 'banquete', 'catering', 0.9),
  ('banquetes', 'banquetes', 'catering_banquetes', 0.92),
  ('coctel', 'coctel', 'catering', 0.88),
  ('cóctel', 'coctel', 'catering', 0.88),
  ('mesas dulces', 'mesas-dulces', 'catering', 0.88),
  ('torta para evento', 'torta-para-evento', 'pasteleria_eventos', 0.9),
  ('pastelería para eventos', 'pasteleria-para-eventos', 'pasteleria_eventos', 0.95),
  ('pasteleria para eventos', 'pasteleria-para-eventos', 'pasteleria_eventos', 0.95),
  ('tortas para matrimonio', 'tortas-para-matrimonio', 'pasteleria_eventos', 0.9),
  ('torta de novios', 'torta-de-novios', 'pasteleria_eventos', 0.92),
  ('mesa de dulces', 'mesa-de-dulces', 'pasteleria_eventos', 0.88),
  -- Animación y fiestas
  ('animación', 'animacion', 'animacion_fiestas', 0.95),
  ('animacion', 'animacion', 'animacion_fiestas', 0.95),
  ('animación infantil', 'animacion-infantil', 'animacion_infantil', 0.95),
  ('animacion infantil', 'animacion-infantil', 'animacion_infantil', 0.95),
  ('animador', 'animador', 'animacion_fiestas', 0.92),
  ('animadora', 'animadora', 'animacion_fiestas', 0.92),
  ('fiesta infantil', 'fiesta-infantil', 'animacion_infantil', 0.92),
  ('cumpleaños de niños', 'cumpleanos-de-ninos', 'animacion_infantil', 0.9),
  ('cumpleanos de ninos', 'cumpleanos-de-ninos', 'animacion_infantil', 0.9),
  ('payaso', 'payaso', 'animacion_infantil', 0.9),
  ('payasos', 'payasos', 'animacion_infantil', 0.9),
  ('títeres', 'titeres', 'animacion_infantil', 0.88),
  ('titeres', 'titeres', 'animacion_infantil', 0.88),
  ('show infantil', 'show-infantil', 'animacion_infantil', 0.9),
  ('globoflexia', 'globoflexia', 'animacion_infantil', 0.88),
  ('pintacaritas', 'pintacaritas', 'animacion_infantil', 0.9),
  ('pinta caritas', 'pinta-caritas', 'animacion_infantil', 0.9),
  ('castillo inflable', 'castillo-inflable', 'animacion_infantil', 0.88),
  ('brinca brinca', 'brinca-brinca', 'animacion_infantil', 0.88),
  ('cama elástica', 'cama-elastica', 'animacion_infantil', 0.85),
  ('cama elastica', 'cama-elastica', 'animacion_infantil', 0.85),
  -- DJ y sonido
  ('dj', 'dj', 'dj_sonido', 0.95),
  ('disc jockey', 'disc-jockey', 'dj_sonido', 0.9),
  ('sonido', 'sonido', 'dj_sonido', 0.88),
  ('sonido para eventos', 'sonido-para-eventos', 'dj_sonido', 0.92),
  ('arriendo de sonido', 'arriendo-de-sonido', 'dj_sonido', 0.9),
  ('música en vivo', 'musica-en-vivo', 'dj_sonido', 0.85),
  ('musica en vivo', 'musica-en-vivo', 'dj_sonido', 0.85),
  ('amplificación', 'amplificacion', 'dj_sonido', 0.85),
  ('iluminación eventos', 'iluminacion-eventos', 'dj_sonido', 0.82),
  ('iluminacion eventos', 'iluminacion-eventos', 'dj_sonido', 0.82),
  ('karaoke', 'karaoke', 'dj_sonido', 0.88),
  ('fiesta con música', 'fiesta-con-musica', 'dj_sonido', 0.85),
  ('fiesta con musica', 'fiesta-con-musica', 'dj_sonido', 0.85),
  -- Decoración de eventos
  ('decoración de eventos', 'decoracion-de-eventos', 'decoracion_eventos', 0.95),
  ('decoracion de eventos', 'decoracion-de-eventos', 'decoracion_eventos', 0.95),
  ('decorador de eventos', 'decorador-de-eventos', 'decoracion_eventos', 0.92),
  ('decoración de salón', 'decoracion-de-salon', 'decoracion_eventos', 0.9),
  ('decoracion de salon', 'decoracion-de-salon', 'decoracion_eventos', 0.9),
  ('decoración fiestas', 'decoracion-fiestas', 'decoracion_eventos', 0.9),
  ('decoracion fiestas', 'decoracion-fiestas', 'decoracion_eventos', 0.9),
  ('centro de mesa', 'centro-de-mesa', 'decoracion_eventos', 0.88),
  ('arreglos para eventos', 'arreglos-para-eventos', 'decoracion_eventos', 0.9),
  ('globos', 'globos', 'decoracion_eventos', 0.85),
  ('decoración bodas', 'decoracion-bodas', 'decoracion_eventos', 0.9),
  ('decoracion bodas', 'decoracion-bodas', 'decoracion_eventos', 0.9),
  ('decoración cumpleaños', 'decoracion-cumpleanos', 'decoracion_eventos', 0.88),
  ('decoracion cumpleanos', 'decoracion-cumpleanos', 'decoracion_eventos', 0.88),
  ('temática', 'tematica', 'decoracion_eventos', 0.85),
  ('tematica', 'tematica', 'decoracion_eventos', 0.85),
  ('ambientación', 'ambientacion', 'decoracion_eventos', 0.88),
  ('ambientacion', 'ambientacion', 'decoracion_eventos', 0.88),
  -- Bar y tragos / carro de comida
  ('bar', 'bar', 'bar_tragos', 0.9),
  ('bar y tragos', 'bar-y-tragos', 'bar_tragos', 0.95),
  ('bar móvil', 'bar-movil', 'bar_tragos', 0.9),
  ('bar movil', 'bar-movil', 'bar_tragos', 0.9),
  ('bar para eventos', 'bar-para-eventos', 'bar_tragos', 0.92),
  ('tragos para eventos', 'tragos-para-eventos', 'bar_tragos', 0.9),
  ('bartender', 'bartender', 'bar_tragos', 0.9),
  ('coctelería', 'cocteleria', 'bar_tragos', 0.88),
  ('cocteleria', 'cocteleria', 'bar_tragos', 0.88),
  ('carro de comida', 'carro-de-comida', 'carro_comida', 0.95),
  ('carro comida', 'carro-comida', 'carro_comida', 0.95),
  ('food truck', 'food-truck', 'food_truck', 0.95),
  ('food truck eventos', 'food-truck-eventos', 'food_truck', 0.9),
  ('camión de comida', 'camion-de-comida', 'carro_comida', 0.9),
  ('camion de comida', 'camion-de-comida', 'carro_comida', 0.9),
  -- Paseos y turismo / camping
  ('paseos', 'paseos', 'paseos_turismo', 0.9),
  ('paseos y turismo', 'paseos-y-turismo', 'paseos_turismo', 0.95),
  ('paseos y turismo', 'paseos-y-turismo', 'paseos_turismo', 0.95),
  ('turismo', 'turismo', 'paseos_turismo', 0.9),
  ('tour', 'tour', 'paseos_turismo', 0.88),
  ('excursión', 'excursion', 'paseos_turismo', 0.88),
  ('excursion', 'excursion', 'paseos_turismo', 0.88),
  ('camping', 'camping', 'camping', 1.0),
  ('camping arriendo', 'camping-arriendo', 'camping', 0.9),
  ('carpa', 'carpa', 'camping', 0.85),
  ('camping familiar', 'camping-familiar', 'camping', 0.88),
  ('campamento', 'campamento', 'camping', 0.85)
) AS v(kw, norm, sub_slug, conf)
JOIN public.subcategorias s ON s.slug = v.sub_slug
ON CONFLICT (normalized_keyword) DO UPDATE SET
  keyword = EXCLUDED.keyword,
  subcategoria_id = EXCLUDED.subcategoria_id,
  confidence_default = EXCLUDED.confidence_default,
  updated_at = now();
