import type { EmprendedorSearchCardProps } from "@/components/search/EmprendedorSearchCard";

const CTA = "/publicar";

/** Ejemplos para home cuando aún no hay suficientes fichas reales (≥6). */
export const HOME_ULTIMOS_PUBLICADOS_MOCK: EmprendedorSearchCardProps[] = [
  {
    slug: "ejemplo-pasteleria",
    nombre: "Pastelería artesanal (ejemplo)",
    fotoPrincipalUrl:
      "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&q=80",
    whatsappPrincipal: "56900000011",
    esFichaCompleta: true,
    estadoFicha: "ficha_completa",
    bloqueTerritorial: null,
    frase: "Tortas y dulces para celebraciones",
    descripcionLibre: "Pedidos con 48 h de anticipación en tu comuna.",
    categoriaNombre: "Gastronomía",
    subcategoriasNombres: ["Repostería"],
    subcategoriasSlugs: ["reposteria"],
    comunaBaseNombre: "Providencia",
    comunaBaseRegionAbrev: "RM",
    atiendeLine: "",
    modalidadesCardBadges: ["A domicilio", "Retiro en local"],
    analyticsSource: "home",
    fichaPublicaHrefOverride: CTA,
  },
  {
    slug: "ejemplo-jardineria",
    nombre: "Jardinería y mantención (ejemplo)",
    fotoPrincipalUrl:
      "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&q=80",
    whatsappPrincipal: "56900000012",
    esFichaCompleta: true,
    estadoFicha: "ficha_completa",
    bloqueTerritorial: null,
    frase: "Diseño de terrazas y riego automático",
    descripcionLibre: "",
    categoriaNombre: "Servicios",
    subcategoriasNombres: ["Jardinería"],
    subcategoriasSlugs: ["jardineria"],
    comunaBaseNombre: "La Florida",
    comunaBaseRegionAbrev: "RM",
    atiendeLine: "",
    modalidadesCardBadges: ["A domicilio"],
    analyticsSource: "home",
    fichaPublicaHrefOverride: CTA,
  },
  {
    slug: "ejemplo-barberia",
    nombre: "Barbería barrio (ejemplo)",
    fotoPrincipalUrl:
      "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=400&q=80",
    whatsappPrincipal: "56900000013",
    esFichaCompleta: false,
    estadoFicha: "ficha_basica",
    bloqueTerritorial: null,
    frase: "Citas por WhatsApp — sin esperas largas",
    descripcionLibre: "",
    categoriaNombre: "Belleza",
    subcategoriasNombres: ["Barbería"],
    subcategoriasSlugs: ["barberia"],
    comunaBaseNombre: "Ñuñoa",
    comunaBaseRegionAbrev: "RM",
    atiendeLine: "",
    analyticsSource: "home",
    fichaPublicaHrefOverride: CTA,
  },
  {
    slug: "ejemplo-mudanzas",
    nombre: "Mudanzas express (ejemplo)",
    fotoPrincipalUrl: "",
    whatsappPrincipal: "56900000014",
    esFichaCompleta: true,
    estadoFicha: "ficha_completa",
    bloqueTerritorial: null,
    frase: "Camión y equipo desde $X en comunas cercanas",
    descripcionLibre: "Embalaje opcional y seguro básico.",
    categoriaNombre: "Servicios",
    subcategoriasNombres: ["Mudanzas"],
    subcategoriasSlugs: ["mudanzas"],
    comunaBaseNombre: "Maipú",
    comunaBaseRegionAbrev: "RM",
    atiendeLine: "",
    modalidadesCardBadges: ["A domicilio"],
    analyticsSource: "home",
    fichaPublicaHrefOverride: CTA,
  },
  {
    slug: "ejemplo-yoga",
    nombre: "Yoga y bienestar (ejemplo)",
    fotoPrincipalUrl:
      "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&q=80",
    whatsappPrincipal: "56900000015",
    esFichaCompleta: true,
    estadoFicha: "ficha_completa",
    bloqueTerritorial: null,
    frase: "Clases grupales y personalizadas",
    descripcionLibre: "",
    categoriaNombre: "Salud",
    subcategoriasNombres: ["Yoga"],
    subcategoriasSlugs: ["yoga"],
    comunaBaseNombre: "Las Condes",
    comunaBaseRegionAbrev: "RM",
    atiendeLine: "",
    modalidadesCardBadges: ["Local físico", "Online"],
    resumenLocalesLinea: "Las Condes · Av. Apoquindo",
    localFisicoComunaNombre: "Las Condes",
    analyticsSource: "home",
    fichaPublicaHrefOverride: CTA,
  },
  {
    slug: "ejemplo-limpieza",
    nombre: "Limpieza post obra (ejemplo)",
    fotoPrincipalUrl:
      "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400&q=80",
    whatsappPrincipal: "56900000016",
    esFichaCompleta: false,
    estadoFicha: "ficha_basica",
    bloqueTerritorial: null,
    frase: "Retiro de escombros y brillo final",
    descripcionLibre: "",
    categoriaNombre: "Servicios",
    subcategoriasNombres: ["Limpieza"],
    subcategoriasSlugs: ["limpieza"],
    comunaBaseNombre: "Puerto Montt",
    comunaBaseRegionAbrev: "Los Lagos",
    atiendeLine: "",
    analyticsSource: "home",
    fichaPublicaHrefOverride: CTA,
  },
  {
    slug: "ejemplo-fotografia",
    nombre: "Fotografía de producto (ejemplo)",
    fotoPrincipalUrl:
      "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&q=80",
    whatsappPrincipal: "56900000017",
    esFichaCompleta: true,
    estadoFicha: "ficha_completa",
    bloqueTerritorial: null,
    frase: "Pack ecommerce y redes sociales",
    descripcionLibre: "Entrega en 5 días hábiles.",
    categoriaNombre: "Servicios",
    subcategoriasNombres: ["Fotografía"],
    subcategoriasSlugs: ["fotografia"],
    comunaBaseNombre: "Valparaíso",
    comunaBaseRegionAbrev: "Valparaíso",
    atiendeLine: "",
    modalidadesCardBadges: ["Local físico", "A domicilio"],
    analyticsSource: "home",
    fichaPublicaHrefOverride: CTA,
  },
  {
    slug: "ejemplo-mascotas",
    nombre: "Peluquería canina (ejemplo)",
    fotoPrincipalUrl:
      "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=400&q=80",
    whatsappPrincipal: "56900000018",
    esFichaCompleta: true,
    estadoFicha: "ficha_completa",
    bloqueTerritorial: null,
    frase: "Baño y corte — agenda semanal",
    descripcionLibre: "",
    categoriaNombre: "Mascotas",
    subcategoriasNombres: ["Peluquería canina"],
    subcategoriasSlugs: ["peluqueria-canina"],
    comunaBaseNombre: "Concepción",
    comunaBaseRegionAbrev: "Biobío",
    atiendeLine: "",
    modalidadesCardBadges: ["Local físico"],
    resumenLocalesLinea: "Concepción · Centro",
    localFisicoComunaNombre: "Concepción",
    analyticsSource: "home",
    fichaPublicaHrefOverride: CTA,
  },
];
