-- =============================================================================
-- Seed: 14 regiones y comunas de Chile (excluye RM y Valparaíso, ya cargadas).
-- Permite que /cobertura muestre avance territorial en todo el país.
-- Comunas sin emprendimientos quedan con estado sin_cobertura en vw_comunas_por_abrir.
-- No modifica la lógica de meta (50 emprendimientos).
-- Región Metropolitana y Valparaíso se insertan/actualizan aparte (ya cargadas).
-- =============================================================================

-- Asegurar UNIQUE(slug) en regiones para ON CONFLICT (comunas usa region_id, nombre)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.regiones'::regclass AND conname = 'regiones_slug_key') THEN
    ALTER TABLE public.regiones ADD CONSTRAINT regiones_slug_key UNIQUE (slug);
  END IF;
EXCEPTION
  WHEN undefined_object THEN NULL;
  WHEN duplicate_object THEN NULL;
END $$;

-- 1) Las 16 regiones (pais requerido por la tabla)
INSERT INTO public.regiones (nombre, slug, pais) VALUES
  ('Región de Arica y Parinacota', 'arica-y-parinacota', 'Chile'),
  ('Región de Tarapacá', 'tarapaca', 'Chile'),
  ('Región de Antofagasta', 'antofagasta', 'Chile'),
  ('Región de Atacama', 'atacama', 'Chile'),
  ('Región de Coquimbo', 'coquimbo', 'Chile'),
  ('Región del Libertador General Bernardo O''Higgins', 'ohiggins', 'Chile'),
  ('Región del Maule', 'maule', 'Chile'),
  ('Región de Ñuble', 'nuble', 'Chile'),
  ('Región del Biobío', 'biobio', 'Chile'),
  ('Región de La Araucanía', 'la-araucania', 'Chile'),
  ('Región de Los Ríos', 'los-rios', 'Chile'),
  ('Región de Los Lagos', 'los-lagos', 'Chile'),
  ('Región Aysén del General Carlos Ibáñez del Campo', 'aysen', 'Chile'),
  ('Región de Magallanes y de la Antártica Chilena', 'magallanes', 'Chile')
ON CONFLICT (slug) DO UPDATE SET nombre = EXCLUDED.nombre, pais = EXCLUDED.pais;

-- 2) Comunas (nombre, slug, region_id). Las que no tengan emprendimientos
-- aparecerán como sin_cobertura en vw_comunas_por_abrir.
INSERT INTO public.comunas (nombre, slug, region_id)
SELECT v.nombre, v.slug, r.id
FROM (VALUES
  ('Arica', 'arica', 'arica-y-parinacota'),
  ('Camarones', 'camarones', 'arica-y-parinacota'),
  ('Putre', 'putre', 'arica-y-parinacota'),
  ('General Lagos', 'general-lagos', 'arica-y-parinacota'),
  ('Iquique', 'iquique', 'tarapaca'),
  ('Alto Hospicio', 'alto-hospicio', 'tarapaca'),
  ('Pozo Almonte', 'pozo-almonte', 'tarapaca'),
  ('Camiña', 'camina', 'tarapaca'),
  ('Colchane', 'colchane', 'tarapaca'),
  ('Huara', 'huara', 'tarapaca'),
  ('Pica', 'pica', 'tarapaca'),
  ('Antofagasta', 'antofagasta', 'antofagasta'),
  ('Mejillones', 'mejillones', 'antofagasta'),
  ('Sierra Gorda', 'sierra-gorda', 'antofagasta'),
  ('Taltal', 'taltal', 'antofagasta'),
  ('Calama', 'calama', 'antofagasta'),
  ('Ollagüe', 'ollagüe', 'antofagasta'),
  ('San Pedro de Atacama', 'san-pedro-de-atacama', 'antofagasta'),
  ('Tocopilla', 'tocopilla', 'antofagasta'),
  ('María Elena', 'maria-elena', 'antofagasta'),
  ('Copiapó', 'copiapo', 'atacama'),
  ('Caldera', 'caldera', 'atacama'),
  ('Tierra Amarilla', 'tierra-amarilla', 'atacama'),
  ('Chañaral', 'chanaral', 'atacama'),
  ('Diego de Almagro', 'diego-de-almagro', 'atacama'),
  ('Vallenar', 'vallenar', 'atacama'),
  ('Alto del Carmen', 'alto-del-carmen', 'atacama'),
  ('Freirina', 'freirina', 'atacama'),
  ('Huasco', 'huasco', 'atacama'),
  ('La Serena', 'la-serena', 'coquimbo'),
  ('Coquimbo', 'coquimbo', 'coquimbo'),
  ('Andacollo', 'andacollo', 'coquimbo'),
  ('La Higuera', 'la-higuera', 'coquimbo'),
  ('Paihuano', 'paihuano', 'coquimbo'),
  ('Vicuña', 'vicuna', 'coquimbo'),
  ('Illapel', 'illapel', 'coquimbo'),
  ('Canela', 'canela', 'coquimbo'),
  ('Los Vilos', 'los-vilos', 'coquimbo'),
  ('Salamanca', 'salamanca', 'coquimbo'),
  ('Ovalle', 'ovalle', 'coquimbo'),
  ('Combarbalá', 'combarbala', 'coquimbo'),
  ('Monte Patria', 'monte-patria', 'coquimbo'),
  ('Punitaqui', 'punitaqui', 'coquimbo'),
  ('Río Hurtado', 'rio-hurtado', 'coquimbo'),
  ('Rancagua', 'rancagua', 'ohiggins'),
  ('Codegua', 'codegua', 'ohiggins'),
  ('Coinco', 'coinco', 'ohiggins'),
  ('Coltauco', 'coltauco', 'ohiggins'),
  ('Doñihue', 'donihue', 'ohiggins'),
  ('Graneros', 'graneros', 'ohiggins'),
  ('Las Cabras', 'las-cabras', 'ohiggins'),
  ('Machalí', 'machali', 'ohiggins'),
  ('Malloa', 'malloa', 'ohiggins'),
  ('Mostazal', 'mostazal', 'ohiggins'),
  ('Olivar', 'olivar', 'ohiggins'),
  ('Peumo', 'peumo', 'ohiggins'),
  ('Pichidegua', 'pichidegua', 'ohiggins'),
  ('Quinta de Tilcoco', 'quinta-de-tilcoco', 'ohiggins'),
  ('Rengo', 'rengo', 'ohiggins'),
  ('Requínoa', 'requinoa', 'ohiggins'),
  ('San Vicente', 'san-vicente', 'ohiggins'),
  ('Pichilemu', 'pichilemu', 'ohiggins'),
  ('La Estrella', 'la-estrella', 'ohiggins'),
  ('Litueche', 'litueche', 'ohiggins'),
  ('Marchihue', 'marchihue', 'ohiggins'),
  ('Navidad', 'navidad', 'ohiggins'),
  ('Paredones', 'paredones', 'ohiggins'),
  ('San Fernando', 'san-fernando', 'ohiggins'),
  ('Chépica', 'chepica', 'ohiggins'),
  ('Chimbarongo', 'chimbarongo', 'ohiggins'),
  ('Lolol', 'lolol', 'ohiggins'),
  ('Nancagua', 'nancagua', 'ohiggins'),
  ('Palmilla', 'palmilla', 'ohiggins'),
  ('Peralillo', 'peralillo', 'ohiggins'),
  ('Placilla', 'placilla', 'ohiggins'),
  ('Pumanque', 'pumanque', 'ohiggins'),
  ('Santa Cruz', 'santa-cruz', 'ohiggins'),
  ('Talca', 'talca', 'maule'),
  ('Constitución', 'constitucion', 'maule'),
  ('Curepto', 'curepto', 'maule'),
  ('Empedrado', 'empedrado', 'maule'),
  ('Maule', 'maule', 'maule'),
  ('Pelarco', 'pelarco', 'maule'),
  ('Pencahue', 'pencahue', 'maule'),
  ('Río Claro', 'rio-claro', 'maule'),
  ('San Clemente', 'san-clemente', 'maule'),
  ('San Rafael', 'san-rafael', 'maule'),
  ('Cauquenes', 'cauquenes', 'maule'),
  ('Chanco', 'chanco', 'maule'),
  ('Pelluhue', 'pelluhue', 'maule'),
  ('Curicó', 'curico', 'maule'),
  ('Hualañé', 'hualane', 'maule'),
  ('Licantén', 'licanten', 'maule'),
  ('Molina', 'molina', 'maule'),
  ('Rauco', 'rauco', 'maule'),
  ('Romeral', 'romeral', 'maule'),
  ('Sagrada Familia', 'sagrada-familia', 'maule'),
  ('Teno', 'teno', 'maule'),
  ('Vichuquén', 'vichuquen', 'maule'),
  ('Linares', 'linares', 'maule'),
  ('Colbún', 'colbun', 'maule'),
  ('Longaví', 'longavi', 'maule'),
  ('Parral', 'parral', 'maule'),
  ('Retiro', 'retiro', 'maule'),
  ('San Javier', 'san-javier', 'maule'),
  ('Villa Alegre', 'villa-alegre', 'maule'),
  ('Yerbas Buenas', 'yerbas-buenas', 'maule'),
  ('Chillán', 'chillan', 'nuble'),
  ('Bulnes', 'bulnes', 'nuble'),
  ('Chillán Viejo', 'chillan-viejo', 'nuble'),
  ('El Carmen', 'el-carmen', 'nuble'),
  ('Pemuco', 'pemuco', 'nuble'),
  ('Pinto', 'pinto', 'nuble'),
  ('Quillón', 'quillon', 'nuble'),
  ('San Ignacio', 'san-ignacio', 'nuble'),
  ('Yungay', 'yungay', 'nuble'),
  ('Quirihue', 'quirihue', 'nuble'),
  ('Cobquecura', 'cobquecura', 'nuble'),
  ('Coelemu', 'coelemu', 'nuble'),
  ('Ninhue', 'ninhue', 'nuble'),
  ('Portezuelo', 'portezuelo', 'nuble'),
  ('Ránquil', 'ranquil', 'nuble'),
  ('Treguaco', 'treguaco', 'nuble'),
  ('San Carlos', 'san-carlos', 'nuble'),
  ('Coihueco', 'coihueco', 'nuble'),
  ('Ñiquén', 'niquen', 'nuble'),
  ('San Fabián', 'san-fabian', 'nuble'),
  ('San Nicolás', 'san-nicolas', 'nuble'),
  ('Concepción', 'concepcion', 'biobio'),
  ('Coronel', 'coronel', 'biobio'),
  ('Chiguayante', 'chiguayante', 'biobio'),
  ('Florida', 'florida', 'biobio'),
  ('Hualqui', 'hualqui', 'biobio'),
  ('Lota', 'lota', 'biobio'),
  ('Penco', 'penco', 'biobio'),
  ('San Pedro de La Paz', 'san-pedro-de-la-paz', 'biobio'),
  ('Santa Juana', 'santa-juana', 'biobio'),
  ('Talcahuano', 'talcahuano', 'biobio'),
  ('Tomé', 'tome', 'biobio'),
  ('Hualpén', 'hualpen', 'biobio'),
  ('Lebu', 'lebu', 'biobio'),
  ('Arauco', 'arauco', 'biobio'),
  ('Cañete', 'canete', 'biobio'),
  ('Contulmo', 'contulmo', 'biobio'),
  ('Curanilahue', 'curanilahue', 'biobio'),
  ('Los Álamos', 'los-alamos', 'biobio'),
  ('Tirúa', 'tirua', 'biobio'),
  ('Los Ángeles', 'los-angeles', 'biobio'),
  ('Antuco', 'antuco', 'biobio'),
  ('Cabrero', 'cabrero', 'biobio'),
  ('Laja', 'laja', 'biobio'),
  ('Mulchén', 'mulchen', 'biobio'),
  ('Nacimiento', 'nacimiento', 'biobio'),
  ('Negrete', 'negrete', 'biobio'),
  ('Quilaco', 'quilaco', 'biobio'),
  ('Quilleco', 'quilleco', 'biobio'),
  ('San Rosendo', 'san-rosendo', 'biobio'),
  ('Santa Bárbara', 'santa-barbara', 'biobio'),
  ('Tucapel', 'tucapel', 'biobio'),
  ('Yumbel', 'yumbel', 'biobio'),
  ('Alto Biobío', 'alto-biobio', 'biobio'),
  ('Temuco', 'temuco', 'la-araucania'),
  ('Carahue', 'carahue', 'la-araucania'),
  ('Cunco', 'cunco', 'la-araucania'),
  ('Curarrehue', 'curarrehue', 'la-araucania'),
  ('Freire', 'freire', 'la-araucania'),
  ('Galvarino', 'galvarino', 'la-araucania'),
  ('Gorbea', 'gorbea', 'la-araucania'),
  ('Lautaro', 'lautaro', 'la-araucania'),
  ('Loncoche', 'loncoche', 'la-araucania'),
  ('Melipeuco', 'melipeuco', 'la-araucania'),
  ('Nueva Imperial', 'nueva-imperial', 'la-araucania'),
  ('Padre Las Casas', 'padre-las-casas', 'la-araucania'),
  ('Perquenco', 'perquenco', 'la-araucania'),
  ('Pitrufquén', 'pitrufquen', 'la-araucania'),
  ('Pucón', 'pucon', 'la-araucania'),
  ('Saavedra', 'saavedra', 'la-araucania'),
  ('Teodoro Schmidt', 'teodoro-schmidt', 'la-araucania'),
  ('Toltén', 'tolten', 'la-araucania'),
  ('Vilcún', 'vilcun', 'la-araucania'),
  ('Villarrica', 'villarrica', 'la-araucania'),
  ('Cholchol', 'cholchol', 'la-araucania'),
  ('Angol', 'angol', 'la-araucania'),
  ('Collipulli', 'collipulli', 'la-araucania'),
  ('Curacautín', 'curacautin', 'la-araucania'),
  ('Ercilla', 'ercilla', 'la-araucania'),
  ('Lonquimay', 'lonquimay', 'la-araucania'),
  ('Los Sauces', 'los-sauces', 'la-araucania'),
  ('Lumaco', 'lumaco', 'la-araucania'),
  ('Purén', 'puren', 'la-araucania'),
  ('Renaico', 'renaico', 'la-araucania'),
  ('Traiguén', 'traiguen', 'la-araucania'),
  ('Victoria', 'victoria', 'la-araucania'),
  ('Valdivia', 'valdivia', 'los-rios'),
  ('Corral', 'corral', 'los-rios'),
  ('Lanco', 'lanco', 'los-rios'),
  ('Los Lagos', 'los-lagos', 'los-rios'),
  ('Máfil', 'mafil', 'los-rios'),
  ('Mariquina', 'mariquina', 'los-rios'),
  ('Paillaco', 'paillaco', 'los-rios'),
  ('Panguipulli', 'panguipulli', 'los-rios'),
  ('La Unión', 'la-union', 'los-rios'),
  ('Futrono', 'futrono', 'los-rios'),
  ('Lago Ranco', 'lago-ranco', 'los-rios'),
  ('Río Bueno', 'rio-bueno', 'los-rios'),
  ('Puerto Montt', 'puerto-montt', 'los-lagos'),
  ('Calbuco', 'calbuco', 'los-lagos'),
  ('Cochamó', 'cochamo', 'los-lagos'),
  ('Fresia', 'fresia', 'los-lagos'),
  ('Frutillar', 'frutillar', 'los-lagos'),
  ('Los Muermos', 'los-muermos', 'los-lagos'),
  ('Llanquihue', 'llanquihue', 'los-lagos'),
  ('Maullín', 'maullin', 'los-lagos'),
  ('Puerto Varas', 'puerto-varas', 'los-lagos'),
  ('Castro', 'castro', 'los-lagos'),
  ('Ancud', 'ancud', 'los-lagos'),
  ('Chonchi', 'chonchi', 'los-lagos'),
  ('Curaco de Vélez', 'curaco-de-velez', 'los-lagos'),
  ('Dalcahue', 'dalcahue', 'los-lagos'),
  ('Puqueldón', 'puqueldon', 'los-lagos'),
  ('Queilén', 'queilen', 'los-lagos'),
  ('Quellón', 'quellon', 'los-lagos'),
  ('Quemchi', 'quemchi', 'los-lagos'),
  ('Quinchao', 'quinchao', 'los-lagos'),
  ('Osorno', 'osorno', 'los-lagos'),
  ('Puerto Octay', 'puerto-octay', 'los-lagos'),
  ('Purranque', 'purranque', 'los-lagos'),
  ('Puyehue', 'puyehue', 'los-lagos'),
  ('Río Negro', 'rio-negro', 'los-lagos'),
  ('San Juan de la Costa', 'san-juan-de-la-costa', 'los-lagos'),
  ('San Pablo', 'san-pablo', 'los-lagos'),
  ('Chaitén', 'chaiten', 'los-lagos'),
  ('Futaleufú', 'futaleufu', 'los-lagos'),
  ('Hualaihué', 'hualaihue', 'los-lagos'),
  ('Palena', 'palena', 'los-lagos'),
  ('Coyhaique', 'coyhaique', 'aysen'),
  ('Lago Verde', 'lago-verde', 'aysen'),
  ('Aysén', 'aysen', 'aysen'),
  ('Cisnes', 'cisnes', 'aysen'),
  ('Guaitecas', 'guaitecas', 'aysen'),
  ('Cochrane', 'cochrane', 'aysen'),
  ('O''Higgins', 'ohiggins-aysen', 'aysen'),
  ('Tortel', 'tortel', 'aysen'),
  ('Chile Chico', 'chile-chico', 'aysen'),
  ('Río Ibáñez', 'rio-ibanez', 'aysen'),
  ('Punta Arenas', 'punta-arenas', 'magallanes'),
  ('Laguna Blanca', 'laguna-blanca', 'magallanes'),
  ('Río Verde', 'rio-verde', 'magallanes'),
  ('San Gregorio', 'san-gregorio', 'magallanes'),
  ('Cabo de Hornos', 'cabo-de-hornos', 'magallanes'),
  ('Antártica', 'antartica', 'magallanes'),
  ('Porvenir', 'porvenir', 'magallanes'),
  ('Primavera', 'primavera', 'magallanes'),
  ('Timaukel', 'timaukel', 'magallanes'),
  ('Natales', 'natales', 'magallanes'),
  ('Torres del Paine', 'torres-del-paine', 'magallanes')
) AS v(nombre, slug, region_slug)
JOIN public.regiones r ON r.slug = v.region_slug
ON CONFLICT (region_id, nombre) DO UPDATE SET
  slug = EXCLUDED.slug
WHERE NOT EXISTS (
  SELECT 1 FROM public.comunas c2
  WHERE c2.slug = EXCLUDED.slug
    AND (c2.region_id, c2.nombre) IS DISTINCT FROM (public.comunas.region_id, public.comunas.nombre)
);
